import test from 'node:test';
import assert from 'node:assert/strict';
import { newWorkspace,beginTurn,buildHistory,forkThread,exportThread,importThread } from '../dist/core/workspace.js';
import { editReply,editPrompt,editSpan,mapEditOffset } from '../dist/core/editing.js';
import { createProject,renameProject,removeProject,moveThread,newProjectThread } from '../dist/core/projects.js';
import { validateWorkspace,LIMITS } from '../dist/core/validation.js';
import { WorkbenchService } from '../desktop/service.mjs';
import { chartSpec,chartSVG } from '../dist/core/visual-tools.js';
function setup(){const w=newWorkspace(),t=w.threads[0];t.settings.model='sample-model';beginTurn(t,'Original question',[{name:'notes.txt',content:'Reference'}]);const turn=t.turns[0],r=turn.replies[0];Object.assign(r,{content:'A first answer.',reasoning:'Actual returned thinking.',status:'complete',finishReason:'stop'});return {w,t,turn,r};}
function request(f,patch={}){return {turnId:f.turn.id,replyId:f.r.id,expectedContent:f.r.content,expectedReasoning:f.r.reasoning,content:'A revised answer.',reasoning:f.r.reasoning,...patch};}
test('answer editing creates a selected continuation branch and preserves original/descendants',()=>{
 const f=setup();beginTurn(f.t,'Later question',[]);f.t.turns[1].replies[0].status='complete';const before=structuredClone(f.t);const b=editReply(f.w,f.t.id,request(f));assert.deepEqual(f.t,before);assert.equal(b.turns.length,1);assert.equal(b.branchOf,f.t.id);assert.equal(b.turns[0].selectedReplyId,f.r.id);assert.equal(b.settings.compare,false);assert.equal(b.turns[0].replies[0].edit.originalContent,f.r.content);
});
test('edited answer is the next turn context exactly once',()=>{const f=setup(),b=editReply(f.w,f.t.id,request(f));const jobs=beginTurn(b,'Continue',[]);assert.equal(jobs[0].messages.filter(m=>m.content==='A revised answer.').length,1);assert.ok(!JSON.stringify(jobs[0].messages).includes('A first answer.'));});
test('thinking revisions are explicit local annotations, not replayed provider reasoning',()=>{const f=setup(),b=editReply(f.w,f.t.id,request(f,{content:f.r.content,reasoning:'My private annotation'}));const r=b.turns[0].replies[0];assert.equal(r.edit.reasoningEdited,true);assert.equal(r.edit.contentEdited,false);assert.equal(r.edit.originalReasoning,f.r.reasoning);assert.ok(!JSON.stringify(buildHistory(b)).includes('My private annotation'));});
test('tool calls/results stay paired while edited narration is not duplicated',()=>{
 const f=setup();f.r.toolMessages=[{role:'assistant',content:'Old narration',reasoning_content:'Tool reasoning',tool_calls:[{id:'call-a',type:'function',function:{name:'render_chart',arguments:'{}'}}]},{role:'tool',tool_call_id:'call-a',content:'Result'}];f.r.finalContentOffset=4;const b=editReply(f.w,f.t.id,request(f));const h=buildHistory(b);assert.equal(h[1].content,'');assert.equal(h[1].tool_calls[0].id,h[2].tool_call_id);assert.equal(h[1].reasoning_content,'Tool reasoning');assert.equal(h.at(-1).content,'A revised answer.');
});
test('stale answer edit is rejected before allocating a branch',()=>{const f=setup();assert.throws(()=>editReply(f.w,f.t.id,request(f,{expectedContent:'different'})),/changed/);assert.equal(f.w.threads.length,1);});
test('stale thinking edit is rejected before allocating a branch',()=>{const f=setup();assert.throws(()=>editReply(f.w,f.t.id,request(f,{expectedReasoning:'different'})),/changed/);assert.equal(f.w.threads.length,1);});
test('unchanged and oversized edits are rejected atomically',()=>{const f=setup();assert.throws(()=>editReply(f.w,f.t.id,request(f,{content:f.r.content})),/Nothing/);assert.throws(()=>editReply(f.w,f.t.id,request(f,{content:'x'.repeat(LIMITS.response),reasoning:'x'})),/Combined/);assert.equal(f.w.threads.length,1);});
test('missing thinking is not fabricated by the editor backend',()=>{const f=setup();f.r.reasoning='';assert.throws(()=>editReply(f.w,f.t.id,request(f,{reasoning:'Invented'})),/no returned/);});
test('streaming and stopped replies cannot silently become completed through editing',()=>{for(const status of ['streaming','queued','stopped','error','awaiting_approval']){const f=setup();f.r.status=status;assert.throws(()=>editReply(f.w,f.t.id,request(f)),/completed/);assert.equal(f.w.threads.length,1);}});
test('re-editing keeps the earliest original content',()=>{const f=setup(),b=editReply(f.w,f.t.id,request(f)),r=b.turns[0].replies[0];const again=editReply(f.w,b.id,{turnId:f.turn.id,replyId:r.id,expectedContent:r.content,expectedReasoning:r.reasoning,content:'Third version',reasoning:r.reasoning});assert.equal(again.turns[0].replies[0].edit.originalContent,'A first answer.');});
test('restoring original text in another branch clears the content override flag',()=>{const f=setup(),b=editReply(f.w,f.t.id,request(f)),r=b.turns[0].replies[0];const restore=editReply(f.w,b.id,{turnId:f.turn.id,replyId:r.id,expectedContent:r.content,expectedReasoning:r.reasoning,content:f.r.content,reasoning:r.reasoning});assert.equal(restore.turns[0].replies[0].edit.contentEdited,false);});
test('prompt edit only creates a draft branch with validated ancestors',()=>{const f=setup();const b=editPrompt(f.w,f.t.id,f.turn.id,'Revised question',f.turn.prompt);assert.equal(b.draft,'Revised question');assert.equal(b.turns.length,0);assert.equal(f.turn.prompt,'Original question');assert.equal(b.branchOf,f.t.id);});
test('empty, stale and unchanged prompt edits do not create threads',()=>{const f=setup();for(const [content,expected] of [['',f.turn.prompt],['New','Wrong'],[f.turn.prompt,f.turn.prompt]])assert.throws(()=>editPrompt(f.w,f.t.id,f.turn.id,content,expected));assert.equal(f.w.threads.length,1);});
test('edit span is linear and handles append, delete, insertion and non-BMP characters',()=>{assert.deepEqual(editSpan('ABC','AxBC'),{start:1,oldEnd:1,newEnd:2});assert.equal(mapEditOffset(3,'ABC','AxBC'),4);assert.equal(mapEditOffset(2,'ABCD','AD'),1);assert.equal(mapEditOffset(4,'😀ok','😀ok!'),4);});
test('artifact insertion offsets shift without losing tool identity',()=>{const f=setup();f.r.tools=[{id:'tool',contentOffset:f.r.content.length}];const b=editReply(f.w,f.t.id,request(f,{content:'Prefix. '+f.r.content}));assert.equal(b.turns[0].replies[0].tools[0].contentOffset,f.r.content.length+8);assert.equal(b.turns[0].replies[0].tools[0].id,'tool');});
test('projects migrate from a 0.5 workspace without resetting conversations',()=>{const f=setup(),old=structuredClone(f.w);delete old.projects;const restored=validateWorkspace(old);assert.deepEqual(restored.projects,[]);assert.equal(restored.threads[0].turns[0].prompt,f.turn.prompt);});
test('create, rename and move project preserve case and reject duplicate names',()=>{const f=setup(),p=createProject(f.w,'  Design  ');assert.equal(p.name,'Design');assert.throws(()=>createProject(f.w,'design'),/already/);renameProject(f.w,p.id,'Build');moveThread(f.w,f.t.id,p.id);assert.equal(f.t.projectId,p.id);assert.equal(f.w.projects[0].name,'Build');});
test('invalid projects fail without changing thread membership',()=>{const f=setup();assert.throws(()=>moveThread(f.w,f.t.id,'missing'),/not found/);assert.equal(f.t.projectId,undefined);assert.throws(()=>createProject(f.w,' '));assert.throws(()=>createProject(f.w,'x'.repeat(81)));});
test('a new conversation keeps the output limit of the one it copies, except the previous default of 8,192',()=>{
  const f=setup();f.t.settings.maxTokens=8192;f.w.activeId=f.t.id;
  const a=newProjectThread(f.w);assert.equal(a.settings.maxTokens,32768);assert.equal(f.t.settings.maxTokens,8192,'the source keeps its own');
  a.settings.maxTokens=16000;assert.equal(newProjectThread(f.w).settings.maxTokens,16000);
});
test('new project threads and edit branches inherit only organizational membership',()=>{const f=setup(),p=createProject(f.w,'Design');moveThread(f.w,f.t.id,p.id);const t=newProjectThread(f.w);assert.equal(t.projectId,p.id);assert.equal(t.settings.systemPrompt,'');const b=editReply(f.w,f.t.id,request(f));assert.equal(b.projectId,p.id);assert.equal(newProjectThread(f.w,null).projectId,null);});
test('removing a project keeps all its threads',()=>{const f=setup(),p=createProject(f.w,'Design');moveThread(f.w,f.t.id,p.id);const content=exportThread(f.t);removeProject(f.w,p.id);assert.equal(f.w.threads.length,1);assert.equal(f.t.projectId,null);assert.equal(f.t.turns[0].prompt,JSON.parse(content).conversation.turns[0].prompt);});
test('workspace validation rejects orphan and duplicate projects',()=>{const f=setup();f.t.projectId='missing';assert.throws(()=>validateWorkspace(f.w),/project/);f.t.projectId=null;const p=createProject(f.w,'Design');f.w.projects.push({...p});assert.throws(()=>validateWorkspace(f.w),/Duplicate project/);});
test('revisions survive export/import while external project and parent links are cleared',()=>{const f=setup(),p=createProject(f.w,'Design');moveThread(f.w,f.t.id,p.id);const b=editReply(f.w,f.t.id,request(f));const imported=importThread(f.w,JSON.parse(exportThread(b)));assert.equal(imported.projectId,null);assert.equal(imported.branchOf,undefined);assert.equal(imported.turns[0].replies[0].edit.originalContent,f.r.content);assert.doesNotThrow(()=>validateWorkspace(f.w));});
test('project count is bounded',()=>{const w=newWorkspace();for(let i=0;i<100;i++)createProject(w,'P'+i);assert.throws(()=>createProject(w,'overflow'),/limit/);});
test('mobile charts use a readable width without changing print geometry',()=>{const spec=chartSpec({title:'Data',type:'line',labels:['A','B','C'],series:[{name:'Samples',values:[1,2,3]}]});assert.match(chartSVG(spec,[],{heading:false,width:360}),/viewBox="0 0 360 250"/);assert.match(chartSVG(spec,[],{width:360,print:true}),/viewBox="0 0 780 430"/);assert.ok(!chartSVG(spec,[],{width:NaN}).includes('NaN'));});
async function service(t){const f=setup();let stored=f.w,calls=0;const vault={read:async()=>structuredClone(stored),write:async w=>{stored=structuredClone(w);},flush:async()=>{}};const s=new WorkbenchService(vault,async()=>{calls++;throw Error('No provider expected');});await s.initialize();t.after(()=>s.shutdown());return {s,get stored(){return stored;},get calls(){return calls;}};}
test('native service snapshots include projects but exclude credentials',async t=>{const f=await service(t);await f.s.execute({type:'project.create',name:'Workbench'});const snapshot=f.s.snapshot();assert.equal(snapshot.workspace.projects[0].name,'Workbench');assert.ok(!('apiKey' in snapshot.workspace));assert.equal(f.calls,0);});
test('native edit commands save branches with no provider request',async t=>{const f=await service(t),s=f.s,thread=s.workspace.threads[0],turn=thread.turns[0],r=turn.replies[0];await s.execute({type:'reply.edit',id:thread.id,turnId:turn.id,replyId:r.id,content:'Changed',reasoning:r.reasoning,expectedContent:r.content,expectedReasoning:r.reasoning});assert.equal(f.stored.threads.length,2);assert.equal(f.calls,0);});
test('native service rejects editing an active thread',async t=>{const {s}=await service(t),thread=s.workspace.threads[0];s.busyThreadId=thread.id;await assert.rejects(s.execute({type:'prompt.edit',id:thread.id,turnId:thread.turns[0].id,content:'Change',expectedContent:thread.turns[0].prompt}),/Stop/);s.busyThreadId=null;});

test('restoring narration after multiple replacements never drops the final model context',()=>{
 const f=setup();f.r.content='Intro\nFinal text';f.r.finalContentOffset=6;f.r.toolMessages=[{role:'assistant',content:'Intro\n',tool_calls:[{id:'call-a',type:'function',function:{name:'render_chart',arguments:'{}'}}]},{role:'tool',tool_call_id:'call-a',content:'Result'}];
 const b=editReply(f.w,f.t.id,request(f,{content:'Replacement'})),r=b.turns[0].replies[0];
 const restored=editReply(f.w,b.id,{turnId:f.turn.id,replyId:r.id,content:f.r.content,reasoning:r.reasoning,expectedContent:r.content,expectedReasoning:r.reasoning});
 const h=buildHistory(restored);assert.equal(h[1].content,'');assert.equal(h.at(-1).content,f.r.content);assert.equal(restored.turns[0].replies[0].edit.contentEdited,false);assert.equal(restored.turns[0].replies[0].edit.historyRewritten,true);
 assert.doesNotThrow(()=>validateWorkspace(f.w));
});
test('thinking-only revisions keep original tool narration and final slice intact',()=>{
 const f=setup();f.r.content='Intro\nFinal text';f.r.finalContentOffset=6;f.r.toolMessages=[{role:'assistant',content:'Intro\n',tool_calls:[{id:'call-a',type:'function',function:{name:'render_chart',arguments:'{}'}}]},{role:'tool',tool_call_id:'call-a',content:'Result'}];
 const b=editReply(f.w,f.t.id,request(f,{content:f.r.content,reasoning:'Local thought annotation'}));const h=buildHistory(b);assert.equal(h[1].content,'Intro\n');assert.equal(h.at(-1).content,'Final text');
});
test('edited provenance flags cannot disagree with original text on import',()=>{const f=setup(),b=editReply(f.w,f.t.id,request(f));b.turns[0].replies[0].edit.contentEdited=false;assert.throws(()=>validateWorkspace(f.w),/Edit flags/);});
test('restored-history routing survives export/import',()=>{const f=setup(),b=editReply(f.w,f.t.id,request(f));const r=b.turns[0].replies[0];r.content=r.edit.originalContent;r.edit.contentEdited=false;r.finalContentOffset=r.content.length;const imported=importThread(f.w,JSON.parse(exportThread(b)));assert.equal(buildHistory(imported).at(-1).content,f.r.content);});
