import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, writeFile, readFile, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CloseCoordinator, persistCloseDecision } from '../desktop/close-coordinator.mjs';
import { inspect } from '../scripts/doctor.mjs';
import { newWorkspace, beginTurn, forkThread } from '../dist/core/workspace.js';
import { validateWorkspace } from '../dist/core/validation.js';
import { WorkbenchService } from '../desktop/service.mjs';
import { EncryptedVault } from '../desktop/vault.mjs';
const root=dirname(dirname(fileURLToPath(import.meta.url)));
const pause=ms=>new Promise(r=>setTimeout(r,ms));
function closeFixture(t,confirmForce=async()=>false,timeoutMs=1000){const notified=[];let closed=0;const c=new CloseCoordinator({notify:id=>notified.push(id),close:()=>closed++,confirmForce,timeoutMs});t.after(()=>c.dispose());return {c,notified,get closed(){return closed;}};}
test('native close waits for an explicit renderer decision',t=>{const f=closeFixture(t);f.c.request();assert.equal(f.closed,0);assert.equal(f.notified.length,1);assert.equal(f.c.reply(f.notified[0],true),true);assert.equal(f.closed,1);});
test('native close ignores duplicate requests while a decision is pending',t=>{const f=closeFixture(t);f.c.request();f.c.request();assert.equal(f.notified.length,1);});
test('keep-open cancels a native close without destroying the window',t=>{const f=closeFixture(t);f.c.request();assert.equal(f.c.reply(f.notified[0],false),true);assert.equal(f.closed,0);assert.equal(f.c.pending,null);});
test('stale and malformed close decisions cannot close a later request',t=>{const f=closeFixture(t);f.c.request();const first=f.notified[0];f.c.reply(first,false);f.c.request();assert.equal(f.c.reply(first,true),false);assert.equal(f.c.reply(f.notified[1],'yes'),false);assert.equal(f.closed,0);f.c.reply(f.notified[1],false);});
test('acknowledgement stops timeout while the person reads the close dialog',async t=>{let prompted=0;const f=closeFixture(t,async()=>{prompted++;return true;},10);f.c.request();f.c.acknowledge(f.notified[0]);await pause(30);assert.equal(prompted,0);assert.equal(f.closed,0);});
test('unresponsive renderer requires a separate native force-close decision',async t=>{let prompted=0;const f=closeFixture(t,async()=>{prompted++;return true;},5);f.c.request();await pause(25);assert.equal(prompted,1);assert.equal(f.closed,1);});
test('declining a native force-close leaves the window open',async t=>{const f=closeFixture(t,async()=>false,5);f.c.request();await pause(25);assert.equal(f.closed,0);assert.equal(f.c.pending,null);});
test('native prompt error fails open without discarding edits',async t=>{const f=closeFixture(t,async()=>{throw Error('dialog error');},5);f.c.request();await pause(25);assert.equal(f.closed,0);});
test('racing fallback paths cannot display two native dialogs',async t=>{let prompted=0,finish;const f=closeFixture(t,()=>{prompted++;return new Promise(r=>finish=r);});f.c.request();const id=f.notified[0];const a=f.c.fallback(id),b=f.c.fallback(id);assert.equal(prompted,1);finish(false);await Promise.all([a,b]);assert.equal(f.closed,0);});
test('disposal invalidates a pending native close response',t=>{const f=closeFixture(t);f.c.request();const id=f.notified[0];f.c.dispose();assert.equal(f.c.reply(id,true),false);assert.equal(f.closed,0);});
test('a late native fallback cannot override renderer cancellation',async t=>{let finish;const f=closeFixture(t,()=>new Promise(r=>finish=r));f.c.request();const id=f.notified[0];const p=f.c.fallback(id);f.c.reply(id,false);finish(true);await p;assert.equal(f.closed,0);});

test('source-only doctor succeeds without pretending native dependencies exist',()=>{const result=inspect(root,{sourceOnly:true});assert.equal(result.ok,true);assert.equal(result.mode,'source-only');assert.ok(result.notChecked.includes('live sign-in and inference'));assert.ok(result.notes[0].includes('optional'));});
test('doctor rejects unsupported Node before local execution',()=>{assert.equal(inspect(root,{sourceOnly:true,nodeVersion:'20.19.0'}).ok,false);assert.equal(inspect(root,{sourceOnly:true,nodeVersion:'22.11.0'}).ok,false);assert.equal(inspect(root,{sourceOnly:true,nodeVersion:'22.12.0'}).ok,true);});
test('dependency doctor rejects a missing lockfile and installation',async t=>{const dir=await mkdtemp(join(tmpdir(),'wb-doctor-test-'));t.after(()=>rm(dir,{recursive:true,force:true}));await writeFile(join(dir,'package.json'),await readFile(join(root,'package.json')));const result=inspect(dir);assert.equal(result.ok,false);assert.ok(result.checks.some(c=>c.name==='Dependency lockfile'&&c.status==='fail'));assert.ok(result.checks.some(c=>c.name==='Electron binary'&&c.status==='fail'));});
test('bootstrap and package scripts no longer float to an unknown major',async()=>{const pkg=JSON.parse(await readFile(join(root,'package.json'),'utf8'));assert.equal(pkg.devDependencies.electron,'44.4.5');assert.equal(pkg.devDependencies['electron-builder'],'26.17.0');const source=await readFile(join(root,'scripts/bootstrap.mjs'),'utf8');assert.ok(!source.includes('@latest'));assert.ok(pkg.scripts['dist:win'].includes('verify:local'));});
test('Windows CI checks lockfile before enabling npm cache',async()=>{const source=await readFile(join(root,'.github/workflows/windows.yml'),'utf8');assert.ok(source.indexOf('Require reviewed dependency lockfile')<source.indexOf('actions/setup-node'));assert.ok(source.includes('npm run doctor'));});
test('current Electron clipboard completion is awaited before reporting success',async()=>{const source=await readFile(join(root,'desktop/main.mjs'),'utf8');assert.ok(source.includes('await clipboard.writeText(value)'));});

test('legacy drafts gain an empty attachment collection',()=>{const w=newWorkspace();delete w.threads[0].draftAttachments;assert.deepEqual(validateWorkspace(w).threads[0].draftAttachments,[]);});
test('draft attachments are validated before persistence',()=>{const w=newWorkspace();w.threads[0].draftAttachments=[{name:'x.md',content:'x'.repeat(250000)}];assert.throws(()=>validateWorkspace(w));});
test('sending moves supplied attachments into a turn and clears only that draft',()=>{const w=newWorkspace(),t=w.threads[0];t.settings.model='test';t.draft='Hello';t.draftAttachments=[{name:'outline.md',content:'reference'}];beginTurn(t,t.draft,t.draftAttachments);assert.deepEqual(t.turns[0].attachments,[{name:'outline.md',content:'reference'}]);assert.deepEqual(t.draftAttachments,[]);assert.equal(t.draft,'');});
test('prompt branches retain reference files without mutating the original',()=>{const w=newWorkspace(),t=w.threads[0];t.settings.model='test';beginTurn(t,'Hi',[{name:'reference.md',content:'notes'}]);const b=forkThread(w,t.id,t.turns[0].id,true);assert.deepEqual(b.draftAttachments,t.turns[0].attachments);b.draftAttachments[0].content='changed';assert.equal(t.turns[0].attachments[0].content,'notes');});
test('failed sends leave the unsent attachments in the draft',()=>{const t=newWorkspace().threads[0];t.settings.model='';t.draftAttachments=[{name:'a.md',content:'retained'}];assert.throws(()=>beginTurn(t,'hello',t.draftAttachments));assert.equal(t.draftAttachments[0].content,'retained');});
test('service draft writes survive reload without any provider call',async t=>{let data=null,calls=0;const vault={read:async()=>structuredClone(data),write:async v=>{data=structuredClone(v);},flush:async()=>{}};const factory=async()=>{calls++;throw Error('not invoked');};const s=new WorkbenchService(vault,factory);await s.initialize();const id=s.workspace.activeId;await s.execute({type:'thread.draft',id,text:'Unsent 中文',attachments:[{name:'context.md',content:'only after Send'}]});await s.shutdown();const again=new WorkbenchService(vault,factory);t.after(()=>again.shutdown());await again.initialize();assert.equal(again.workspace.threads[0].draft,'Unsent 中文');assert.equal(again.workspace.threads[0].draftAttachments[0].content,'only after Send');assert.equal(calls,0);});
test('text-only draft updates preserve references; explicit empty list removes them',async t=>{let data=null;const vault={read:async()=>data,write:async v=>{data=structuredClone(v);},flush:async()=>{}};const s=new WorkbenchService(vault,async()=>{throw Error('offline');});await s.initialize();t.after(()=>s.shutdown());const id=s.workspace.activeId;await s.execute({type:'thread.draft',id,text:'a',attachments:[{name:'x.md',content:'reference'}]});await s.execute({type:'thread.draft',id,text:'b'});assert.equal(s.workspace.threads[0].draftAttachments.length,1);await s.execute({type:'thread.draft',id,text:'c',attachments:[]});assert.equal(s.workspace.threads[0].draftAttachments.length,0);});
test('draft text and references use the existing encrypted vault envelope',async t=>{const dir=await mkdtemp(join(tmpdir(),'wb-handoff-vault-'));t.after(()=>rm(dir,{recursive:true,force:true}));const protector={isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(s),decryptString:b=>b.toString()};const v=new EncryptedVault(dir,protector);await v.read();const w=newWorkspace();w.threads[0].draft='private-draft-probe';w.threads[0].draftAttachments=[{name:'probe.md',content:'private-reference-probe'}];await v.write(w);const raw=await readFile(v.path,'utf8');assert.ok(!raw.includes('private-draft-probe'));assert.ok(!raw.includes('private-reference-probe'));assert.equal((await new EncryptedVault(dir,protector).read()).threads[0].draftAttachments[0].content,'private-reference-probe');});

test('renderer becoming unresponsive after acknowledgement retains a native escape path',async()=>{const source=await readFile(join(root,'desktop/main.mjs'),'utf8');assert.ok(source.includes("window.on('unresponsive'"));assert.ok(source.includes('closeCoordinator.fallback(closeCoordinator.pending)'));});

test('main close decision cannot bypass a disk failure after a failure snapshot',async t=>{const f=closeFixture(t);f.c.request();const id=f.notified[0];await assert.rejects(persistCloseDecision(f.c,id,true,async()=>{throw Error('disk full');}),/disk full/);assert.equal(f.closed,0);assert.equal(f.c.pending,null);});
test('main close persists again even if the renderer had no dirty draft',async t=>{const f=closeFixture(t);f.c.request();let written=0;assert.equal(await persistCloseDecision(f.c,f.notified[0],true,async()=>{written++;assert.equal(f.closed,0);}),true);assert.equal(written,1);assert.equal(f.closed,1);});
test('keep-open does not perform an unnecessary durability write',async t=>{const f=closeFixture(t);f.c.request();let writes=0;assert.equal(await persistCloseDecision(f.c,f.notified[0],false,async()=>{writes++;}),true);assert.equal(writes,0);assert.equal(f.closed,0);});
test('cancellation while a final durability write waits cannot close later',async t=>{const f=closeFixture(t);f.c.request();const id=f.notified[0];let complete;const pending=persistCloseDecision(f.c,id,true,()=>new Promise(r=>complete=r));f.c.reply(id,false);f.c.request();complete();assert.equal(await pending,false);assert.equal(f.closed,0);assert.equal(f.c.pending,f.notified[1]);});
