import test from 'node:test';
import assert from 'node:assert/strict';
import { markdown, extractCodeBlocks, safeExternalURL } from '../dist/core/markdown.js';
import { defaultView, viewPreferences } from '../dist/core/preferences.js';
import { newWorkspace, beginTurn, importThread, exportThread, recoverInterrupted } from '../dist/core/workspace.js';
import { validateWorkspace, validateArtifact } from '../dist/core/validation.js';
import { ToolCallAccumulator, pythonArguments } from '../dist/core/tools.js';

test('minimal preferences default to folded reasoning and hidden advanced metadata',()=>{
 const v=viewPreferences(undefined);assert.equal(v.inspector,false);assert.equal(v.metadata,false);assert.equal(v.reasoning,'collapsed');assert.equal(v.math,true);
 assert.deepEqual(viewPreferences({inspector:'true',reasoning:'invented',secret:1}),defaultView);
});
test('old workspace migrates additively with execution off',()=>{const w=newWorkspace();delete w.view;delete w.pythonPath;delete w.threads[0].settings.toolsMode;const restored=validateWorkspace(w);assert.equal(restored.pythonPath,'');assert.equal(restored.view.reasoning,'collapsed');assert.equal(restored.threads[0].settings.toolsMode,'off');});
test('GFM tables, nested lists, blockquotes, tasks and strikethrough render',()=>{const html=markdown('| A | B |\n|---|---|\n| 1 | 2 |\n\n- parent\n  - child\n\n> quote\n\n- [x] done\n\n~~old~~');for(const token of ['<table>','<blockquote>','disabled','<del>'])assert.ok(html.includes(token),token);});
test('LaTeX inline and display forms become native MathML offline',()=>{for(const input of ['$x^2$','$$\\frac{1}{2}$$','\\(x^2\\)','\\[\\sum_{i=1}^n i\\]']){const html=markdown(input);assert.match(html,/<math\b/);assert.ok(!html.includes('<img'));assert.match(html,/data-tex=/);}});
test('math does not interpret code spans or code fences',()=>{for(const input of ['`$x$`','```python\nprint("$x$")\n```'])assert.ok(!markdown(input).includes('<math'));assert.ok(!markdown('Costs $20 and $30.').includes('<math'));});
test('unsupported math and partial streaming input preserve original TeX',()=>{const html=markdown('$\\unknownmacro{a}$');assert.match(html,/math-error/);assert.match(html,/unknownmacro/);assert.doesNotThrow(()=>markdown('$$\\frac{a}'));assert.ok(!markdown('$x$',{math:false}).includes('<math'));});
test('LaTeX HTML and external-link commands cannot introduce executable markup',()=>{for(const s of ['$\\href{javascript:alert(1)}{click}$','$\\htmlClass{evil}{x}$','$\\includegraphics{https://evil.test/x}$']){const html=markdown(s);assert.ok(!/<a\s|<img\s|<script\b|class="evil"/.test(html));}});
test('links are explicit buttons, remote images placeholders, embedded HTML escaped',()=>{const html=markdown('[safe](https://example.org/page) [bad](javascript:alert(1))\n\n![tracker](https://evil.test/x)\n\n<iframe src="https://evil.test"></iframe>');assert.match(html,/data-url="https:\/\/example.org\/page"/);assert.ok(!/<(?:img|iframe|a)\b/.test(html));assert.ok(!html.includes('data-url="javascript:'));});
test('external URL validation rejects credentials, controls and non-HTTP schemes',()=>{for(const s of ['file:///etc/passwd','javascript:alert(1)','data:text/html,hi','https://user:pass@example.com','https://exa\nmple.org','//example.com'])assert.equal(safeExternalURL(s),null);assert.equal(safeExternalURL('https://example.com/a'),'https://example.com/a');});
test('code is highlighted and Python execution actions are separate from rendering',()=>{const html=markdown('```python\nprint("hello")\n```');assert.match(html,/token/);assert.match(html,/run-code/);assert.ok(!markdown('```python\nprint(1)\n```',{codeTools:false}).includes('run-code'));});
test('block extraction preserves nested source and renderer indexes',()=>{const s='```json\n{}\n```\n\n> ```python\n> print("nested")\n> ```';assert.deepEqual(extractCodeBlocks(s),[{language:'json',code:'{}'},{language:'python',code:'print("nested")'}]);assert.match(markdown(s),/data-code-index="1"/);});
test('display parsing is bounded without modifying stored source',()=>{const input='x'.repeat(200001);assert.match(markdown(input),/Display shortened/);assert.equal(input.length,200001);});
test('fragmented tool calls assemble independently in stable index order',()=>{const a=new ToolCallAccumulator();a.add([{index:1,id:'two',type:'function',function:{name:'python',arguments:'{"code":"p'}},{index:0,id:'one',type:'function',function:{name:'py',arguments:'{"code":"print(1)"}'}}]);a.add([{index:1,function:{arguments:'rint(2)"}'}},{index:0,function:{name:'thon'}}]);const calls=a.finish();assert.deepEqual(calls.map(c=>c.id),['one','two']);assert.equal(pythonArguments(calls[1].function.arguments).code,'print(2)');});
test('a response may make four calls to the ordinary tools, or as many as the accumulator is given',()=>{const call=i=>({index:i,id:'c'+i,type:'function',function:{name:'python',arguments:'{}'}});assert.throws(()=>new ToolCallAccumulator().add([call(4)]),/more than 4 tool calls/);const a=new ToolCallAccumulator(16);a.add(Array.from({length:16},(_,i)=>call(i)));assert.equal(a.finish().length,16);assert.throws(()=>new ToolCallAccumulator(16).add([call(16)]),/more than 16 tool calls/);});
test('invalid tool streams fail closed',()=>{for(const part of [[{index:4}], [{index:0,id:'x',type:'custom'}], [{index:0,id:'x',function:{name:'python',arguments:3}}]])assert.throws(()=>new ToolCallAccumulator().add(part));const a=new ToolCallAccumulator();a.add([{index:0,id:'x',function:{name:'python',arguments:'{}'}}]);assert.throws(()=>a.add([{index:0,id:'y'}]));const b=new ToolCallAccumulator();b.add([{index:0,id:'x',function:{name:'p'}},{index:1,id:'x',function:{name:'p'}}]);assert.throws(()=>b.finish());});
test('Python schema rejects extra arguments, empty code and oversized payloads',()=>{for(const s of ['{}','[]','null','{','{"code":""}','{"code":"print(1)","shell":true}',JSON.stringify({code:'x'.repeat(64001)}),JSON.stringify({code:'a\0b'})])assert.throws(()=>pythonArguments(s));assert.deepEqual(pythonArguments('{"code":"print(1)"}'),{code:'print(1)'});});
test('artifacts reject unsupported MIME, traversal and malformed base64',()=>{const base={id:'a',name:'out.txt',mime:'text/plain',data:'aGk='};assert.deepEqual(validateArtifact(base),base);for(const patch of [{name:'../x'},{mime:'application/x-msdownload'},{data:'???'},{data:'a'}])assert.throws(()=>validateArtifact({...base,...patch}));});
test('import and crash recovery never resume tool approvals',()=>{const w=newWorkspace(),t=w.threads[0];t.settings.model='a';beginTurn(t,'hi',[]);const r=t.turns[0].replies[0];r.status='awaiting_approval';r.tools=[{id:'tool',callId:'call',name:'python',arguments:'{"code":"print(1)"}',origin:'model',status:'awaiting_approval',stdout:'',stderr:'',exitCode:null,elapsedMs:0,artifacts:[],truncated:false}];const imported=importThread(w,JSON.parse(exportThread(t)));assert.equal(imported.turns[0].replies[0].tools[0].status,'cancelled');assert.notEqual(imported.turns[0].replies[0].tools[0].id,'tool');assert.equal(recoverInterrupted(w),true);assert.equal(r.tools[0].status,'cancelled');assert.equal(r.status,'interrupted');});
