import test from 'node:test';
import assert from 'node:assert/strict';
import { RenderCache } from '../dist/core/render-cache.js';
import { RenderScheduler, streamingInterval } from '../dist/renderer/render-scheduler.js';
import { markdown, clearMarkdownCaches } from '../dist/core/markdown.js';
import { chartSpec, chartSVG, diagramSpec, diagramSVG, VISUAL_TOOLS } from '../dist/core/visual-tools.js';

test('render cache evicts least recently used entries under both limits',()=>{
 const cache=new RenderCache(2,10);cache.set('a','A',4);cache.set('b','B',4);assert.equal(cache.get('a'),'A');cache.set('c','C',4);assert.equal(cache.get('b'),undefined);assert.equal(cache.cost,8);assert.equal(cache.size,2);
 cache.set('d','D',9);assert.equal(cache.size,1);assert.equal(cache.cost,9);
});
test('render cache updates accounting, rejects oversize entries and clears',()=>{
 const cache=new RenderCache(4,20);cache.set('a','old',10);cache.set('a','new',6);assert.equal(cache.cost,6);cache.set('big','no',21);assert.equal(cache.size,1);cache.set('bad','no',NaN);assert.equal(cache.size,1);cache.clear();assert.equal(cache.cost,0);assert.equal(cache.get('a'),undefined);assert.throws(()=>new RenderCache(0));
});
test('cached maths and highlighting preserve source indexing and safety',()=>{
 clearMarkdownCaches();const input='A $x^2$\n\n```python\nprint(2)\n```';const a=markdown(input);assert.equal(markdown(input),a);assert.match(markdown(input+'\n\n```python\nprint(2)\n```'),/data-code-index="1"/);assert.doesNotMatch(markdown(input,{math:false}),/<math/);assert.match(markdown(input),/<math/);assert.doesNotMatch(markdown(input,{codeTools:false}),/run-code/);clearMarkdownCaches();assert.equal(markdown(input),a);
});
function fixture(){let time=0,hidden=false,id=0,paints=0;const frames=new Map(),timers=new Map();const host={now:()=>time,hidden:()=>hidden,frame:fn=>{frames.set(++id,fn);return id;},cancelFrame:n=>frames.delete(n),later:(fn,delay)=>{timers.set(++id,{fn,due:time+delay});return id;},cancelLater:n=>timers.delete(n)};const scheduler=new RenderScheduler(()=>paints++,host);return{scheduler,frames,timers,get paints(){return paints;},hide(v){hidden=v;},advance(ms){time+=ms;for(const [n,t]of[...timers])if(t.due<=time){timers.delete(n);t.fn();}},frame(){for(const [n,fn]of[...frames]){frames.delete(n);fn();}}};}
test('stream scheduler coalesces bursts, is idle between events, and retains final paint',()=>{const f=fixture();for(let i=0;i<100;i++)f.scheduler.request();assert.equal(f.frames.size,1);f.frame();assert.equal(f.paints,1);assert.equal(f.frames.size,0);f.scheduler.request();assert.equal(f.timers.size,1);f.advance(32);f.frame();assert.equal(f.paints,2);});
test('urgent completion cancels throttling rather than delaying final output',()=>{const f=fixture();f.scheduler.request();f.frame();f.scheduler.request();assert.equal(f.timers.size,1);f.scheduler.request(32,true);assert.equal(f.timers.size,0);assert.equal(f.frames.size,1);f.frame();assert.equal(f.paints,2);});
test('background work is deferred until visible and no timer loop remains',()=>{const f=fixture();f.hide(true);f.scheduler.request();assert.equal(f.frames.size+f.timers.size,0);f.hide(false);f.scheduler.request(32,true);f.frame();assert.equal(f.paints,1);f.scheduler.request();f.scheduler.destroy();assert.equal(f.frames.size+f.timers.size,0);});
test('scheduler checks visibility again between timer and frame',()=>{const f=fixture();f.scheduler.request();f.hide(true);f.frame();assert.equal(f.paints,0);f.hide(false);f.scheduler.request(32,true);f.frame();assert.equal(f.paints,1);assert.equal(streamingInterval(5000),32);assert.equal(streamingInterval(50000),64);});
test('SVG chart canvas is transparent and neutral rules replace blue panels',()=>{const svg=chartSVG(chartSpec({title:'A',type:'line',labels:['1','2'],series:[{name:'a',values:[1,2]}]}));assert.doesNotMatch(svg,/<rect width="100%"|#101c30|#253954/);assert.match(svg,/#363636/);assert.match(svg,/data-key="series-0"/);});
test('dense line charts omit redundant dots without dropping coordinates or isolated points',()=>{const labels=Array.from({length:200},(_,i)=>String(i));const spec=chartSpec({title:'Dense',type:'line',labels,series:[{name:'s',values:labels.map(Number)}]});const svg=chartSVG(spec);assert.doesNotMatch(svg,/<circle/);assert.match(svg,/<polyline points="[^"]+"/);const isolated={...spec,series:[{name:'s',values:labels.map((_,i)=>i===100?9:null)}]};assert.match(chartSVG(isolated),/<circle/);const scatter={...spec,type:'scatter'};assert.equal((chartSVG(scatter).match(/<circle/g)||[]).length,200);});
test('diagram uses neutral nodes without an enclosing background rectangle',()=>{const svg=diagramSVG(diagramSpec({title:'D',nodes:[{id:'a',label:'One'},{id:'b',label:'Two'}],edges:[{from:'a',to:'b'}]}));assert.match(svg,/#292929/);assert.doesNotMatch(svg,/#142b47|width="100%"/);});
test('model artifact guidance prefers seamless neutral structured output',()=>{const help=VISUAL_TOOLS.find(t=>t.function.name==='create_artifact').function.description;assert.match(help,/transparent background/);assert.match(help,/structured chart\/table\/diagram/);assert.doesNotMatch(help,/dark-blue|#101c30/);});
test('transparent structured charts use a separate readable palette for white PDF pages',()=>{const spec=chartSpec({title:'Print',type:'bar',labels:['a'],series:[{name:'s',values:[4]}]});const svg=chartSVG(spec,[],{print:true});assert.match(svg,/fill="#242424"/);assert.match(svg,/fill="#2a78d6"/);assert.doesNotMatch(svg,/fill="#d4d4d4"|width="100%"/);});
test('print diagram palette keeps light nodes and dark text without changing label contents',()=>{const spec=diagramSpec({title:'D',nodes:[{id:'a',label:'#292929'}],edges:[]});const svg=diagramSVG(spec,'print',true,true);assert.match(svg,/fill="#f2f2f2"/);assert.match(svg,/>#292929</);});
