import test from 'node:test';
import assert from 'node:assert/strict';
import { WorkbenchService } from '../desktop/service.mjs';
import { buildHistory } from '../dist/core/workspace.js';
import { validateWorkspace } from '../dist/core/validation.js';
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const done=async s=>{while(s.tasks.size)await Promise.all([...s.tasks]);};
const nextApproval=async s=>{for(let i=0;i<500;i++){if(s.approvals.size)return [...s.approvals.values()][0];await wait(2);}throw Error('Approval not produced');};
const chunk=(delta,finish_reason)=>({choices:[{delta,finish_reason}]});
const result={status:'complete',stdout:'2\n',stderr:'',exitCode:0,elapsedMs:2,artifacts:[],truncated:false};
function toolChunk(name='python',args='{"code":"print(1+1)"}',id='call_1'){return chunk({tool_calls:[{index:0,id,type:'function',function:{name,arguments:args}}]},'tool_calls');}
async function setup(t,{generator,runner,mode='ask'}={}){
 const requests=[],executions=[];let stored=null;
 const vault={read:async()=>null,write:async w=>{stored=structuredClone(w);},flush:async()=>{}};
 const client={ready:async()=>{},getVerificationDocument:async()=>({securityVerified:true,steps:{}}),chat:{completions:{create:async body=>{requests.push(structuredClone(body));return generator?generator(requests.length,body):(async function*(){if(requests.length===1)yield toolChunk();else yield chunk({content:'The result is 2.'},'stop');})();}}}};
 const s=new WorkbenchService(vault,async()=>client,()=>{},async input=>{executions.push(input);return runner?runner(input):result;});await s.initialize();s.workspace.apiKey='fixture-key';s.workspace.pythonPath='/fixture/python';Object.assign(s.workspace.threads[0].settings,{model:'fixture',toolsMode:mode,visualTools:false});t.after(()=>s.shutdown());
 return {s,requests,executions,get stored(){return stored;}};
}
const send=s=>s.execute({type:'send',id:s.workspace.activeId,text:'Compute two.',attachments:[]});
const approve=(s,p,allow)=>s.execute({type:'tool.approve',id:p.threadId,toolId:p.tool.id,approve:allow});
const reply=s=>s.workspace.threads[0].turns[0].replies[0];

test('tool proposal cannot execute before explicit approval',async t=>{const {s,executions}=await setup(t);await send(s);const p=await nextApproval(s);await wait(20);assert.equal(executions.length,0);assert.equal(reply(s).status,'awaiting_approval');assert.equal(p.tool.name,'python');await approve(s,p,false);await done(s);assert.equal(executions.length,0);assert.equal(p.tool.status,'denied');});
test('approved tool result returns in matched protocol history and produces final answer',async t=>{const {s,executions,requests}=await setup(t);await send(s);const p=await nextApproval(s);await approve(s,p,true);await done(s);assert.equal(executions.length,1);assert.equal(executions[0].code,'print(1+1)');assert.equal(requests.length,2);assert.equal(requests[1].messages[2].tool_calls[0].id,'call_1');assert.equal(requests[1].messages[3].tool_call_id,'call_1');assert.equal(JSON.parse(requests[1].messages[3].content).stdout,'2\n');assert.equal(reply(s).content,'The result is 2.');assert.equal(reply(s).status,'complete');assert.deepEqual(buildHistory(s.workspace.threads[0]).map(m=>m.role),['user','assistant','tool','assistant']);assert.doesNotThrow(()=>validateWorkspace(s.workspace));});
test('stale and cross-thread approval messages cannot execute',async t=>{const {s,executions}=await setup(t);await send(s);const p=await nextApproval(s);await assert.rejects(s.execute({type:'tool.approve',id:'different',toolId:p.tool.id,approve:true}));await approve(s,p,true);await assert.rejects(approve(s,p,true));await done(s);assert.equal(executions.length,1);});
test('stop while awaiting approval cancels without executing',async t=>{const {s,executions}=await setup(t);await send(s);const p=await nextApproval(s);await s.execute({type:'stop',id:s.workspace.activeId});await done(s);assert.equal(p.tool.status,'cancelled');assert.equal(executions.length,0);assert.equal(s.approvals.size,0);assert.equal(reply(s).status,'stopped');});
test('tool capability is not offered when mode is off',async t=>{const {s,requests,executions}=await setup(t,{mode:'off'});await send(s);await done(s);assert.ok(!('tools'in requests[0]));assert.equal(s.approvals.size,0);assert.equal(executions.length,0);assert.equal(reply(s).status,'interrupted');});
test('unknown tools and malformed Python are never approved or executed',async t=>{for(const [name,args] of [['shell','{"code":"whoami"}'],['python','not json']]){const {s,executions}=await setup(t,{generator:async function*(n){yield n===1?toolChunk(name,args):chunk({content:'No tool ran.'},'stop');}});await send(s);await done(s);assert.equal(s.approvals.size,0);assert.equal(executions.length,0);assert.equal(reply(s).tools[0].status,'error');assert.equal(reply(s).status,'complete');}});
test('execution failures are returned to the model without fabricated output',async t=>{const {s,requests}=await setup(t,{runner:async()=>({...result,status:'error',stdout:'',stderr:'ModuleNotFoundError',exitCode:1})});await send(s);await approve(s,await nextApproval(s),true);await done(s);assert.equal(JSON.parse(requests[1].messages[3].content).status,'error');assert.equal(reply(s).tools[0].stdout,'');});
test('provider-reported usage is summed across tool rounds',async t=>{const {s}=await setup(t,{generator:async function*(n){yield n===1?toolChunk():chunk({content:'Done'},'stop');yield {choices:[],usage:{prompt_tokens:n*10,completion_tokens:n*2}};}});await send(s);await approve(s,await nextApproval(s),true);await done(s);assert.deepEqual(reply(s).usage,{input:30,output:6});});
test('tool round budget prevents endless approvals',async t=>{const {s,executions}=await setup(t,{generator:async function*(n){yield toolChunk('python','{"code":"print(1)"}','call_'+n);}});await send(s);for(let i=0;i<4;i++)await approve(s,await nextApproval(s),true);await done(s);assert.equal(executions.length,4);assert.equal(reply(s).status,'error');assert.match(reply(s).error,/budget/);assert.equal(s.approvals.size,0);});
test('manual code execution derives exact stored block and does not inject results into model history',async t=>{const {s,executions}=await setup(t,{generator:async function*(){yield chunk({content:'```python\nprint(7)\n```'},'stop');}});await send(s);await done(s);const r=reply(s);await s.execute({type:'code.run',id:s.workspace.activeId,replyId:r.id,index:0,code:'print("injected")'});await approve(s,await nextApproval(s),true);await done(s);assert.equal(executions[0].code,'print(7)');assert.equal(r.tools[0].origin,'manual');assert.equal(buildHistory(s.workspace.threads[0]).length,2);assert.equal(r.status,'complete');});
test('snapshot does not expose interpreter path or API secrets',async t=>{const {s}=await setup(t);const snapshot=s.snapshot();assert.equal(snapshot.pythonConfigured,true);assert.ok(!JSON.stringify(snapshot).includes('/fixture/python'));assert.ok(!JSON.stringify(snapshot).includes('fixture-key'));});
test('model-provided reasoning is retained independently of tool outputs',async t=>{const {s}=await setup(t,{generator:async function*(n){yield chunk({reasoning_content:n===1?'First thought.':'After tool.'});yield n===1?toolChunk():chunk({content:'Final'},'stop');}});await send(s);await approve(s,await nextApproval(s),true);await done(s);assert.match(reply(s).reasoning,/First thought/);assert.match(reply(s).reasoning,/After tool/);assert.equal(reply(s).toolMessages[0].reasoning_content,'First thought.');assert.ok(!reply(s).content.includes('thought'));});
test('missing interpreter blocks tool-enabled sends before inference or history mutation',async t=>{const {s,requests}=await setup(t);s.workspace.pythonPath='';await assert.rejects(send(s),/Choose an installed Python/);assert.equal(requests.length,0);assert.equal(s.workspace.threads[0].turns.length,0);});
test('running tool receives cancellation signal and cannot turn cancellation into a completed reply',async t=>{let started=false;const {s}=await setup(t,{runner:async({signal})=>{started=true;await new Promise(resolve=>signal.addEventListener('abort',resolve,{once:true}));return {...result,status:'cancelled'};}});await send(s);await approve(s,await nextApproval(s),true);while(!started)await wait(2);await s.execute({type:'stop',id:s.workspace.activeId});await done(s);assert.equal(reply(s).status,'stopped');assert.equal(reply(s).tools[0].status,'cancelled');assert.equal(s.busyThreadId,null);});
