"""Production renderer + synthetic memory-only fixtures. No native/provider calls."""
import argparse,json
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
parser=argparse.ArgumentParser();parser.add_argument('--chromium',default=None);args=parser.parse_args()
root=Path(__file__).resolve().parents[1];html=(root/'preview/index.html').read_text(encoding='utf-8');checks=[];errors=[]
marker='const pause = (ms) => new Promise((r) => setTimeout(r, ms));'
fixture=r'''window.__inspect=()=>structuredClone(workspace);
window.__seed=()=>{const t=workspace.threads.find(t=>t.id===workspace.activeId);t.title='Repair analysis';t.turns=[{id:'test-turn',prompt:'Explain the repair measurements. 中文输入。',attachments:[{name:'observations.csv',content:'142,180,218'}],createdAt:Date.now(),selectedReplyId:'test-reply',replies:[{id:'test-reply',model:'demo/writer',content:'The sample mean is **180 seconds**.\n\n$$x = 180$$\n\nThis is synthetic demonstration text.',reasoning:'Synthetic returned thinking: separate the arithmetic from the scheduling assumption.',status:'complete',finishReason:'stop',error:null,usage:null,elapsedMs:1234,tools:[],toolMessages:[]}]}];emit();};
window.__changeReply=()=>{workspace.threads.find(t=>t.id===workspace.activeId).turns[0].replies[0].content+=' A concurrent update.';emit();};
window.__busy=value=>{busy=value?workspace.activeId:null;emit();};
window.__dropReply=()=>{const t=workspace.threads.find(t=>t.id===workspace.activeId);t.turns[0].replies[0].id='gone';t.turns[0].selectedReplyId='gone';emit();};
'''
assert marker in html;html=html.replace(marker,marker+fixture,1)
with sync_playwright() as p:
 b=p.chromium.launch(executable_path=args.chromium,headless=True,args=['--no-sandbox']);page=b.new_page(viewport={'width':1440,'height':1000});page.on('pageerror',lambda e:errors.append(str(e)))
 page.set_content(html);page.evaluate('window.__seed()');original=page.evaluate('window.__inspect()')
 expect(page.locator('.nav-section-heading h2').first).to_have_text('Projects');expect(page.locator('#thread-title')).to_have_text('Repair analysis');checks.append('project and thread headings expose a real active thread title')
 reply=page.locator('#reply-test-reply');page.locator('[data-action=edit-reply]').click();expect(reply.locator('.inline-editor')).to_be_visible();expect(page.locator('#edit-dialog')).to_be_hidden()
 expect(page.locator('#inline-content')).to_have_value(original['threads'][0]['turns'][0]['replies'][0]['content']);expect(page.locator('#inline-reasoning')).to_have_value(original['threads'][0]['turns'][0]['replies'][0]['reasoning']);expect(page.locator('#inline-content')).to_be_focused()
 checks.append('Edit opens the answer and its thinking text in place of the reply, not in a dialog')
 value='A revised **answer** with $x=216$.\n\n<script>window.injected=true</script>'
 page.locator('#inline-content').fill(value);page.locator('#inline-reasoning').fill('My local correction, not new model output.');page.evaluate('window.__busy(false)');page.wait_for_timeout(200)
 expect(page.locator('#inline-content')).to_have_value(value);expect(page.locator('#inline-reasoning')).to_have_value('My local correction, not new model output.');checks.append('a snapshot while editing leaves the fields and their text alone')
 page.locator('#inline-content').press('Escape');expect(page.locator('.inline-editor-discard')).to_be_visible();page.locator('[data-action=inline-keep]').click();expect(page.locator('.inline-editor-discard')).to_be_hidden();expect(page.locator('#inline-content')).to_have_value(value);checks.append('Escape asks before discarding an edited answer and keeps the text')
 page.locator('#inline-content').press('Control+Enter');expect(page.locator('.inline-editor')).to_have_count(0);w=page.evaluate('window.__inspect()');thread=w['threads'][0];assert len(w['threads'])==1 and len(thread['turns'])==1
 assert thread['turns'][0]['version']==2 and thread['turns'][0]['versions']==[{'turns':original['threads'][0]['turns']}];assert not page.evaluate('Boolean(window.injected)')
 expect(page.locator('.edited-label')).to_be_visible();expect(page.locator('.reply .version-pager')).to_contain_text('2/2');expect(page.locator('.user-row .version-pager')).to_have_count(0);expect(page.locator('#branch-origin')).to_be_hidden()
 checks.append('saving makes version 2 of the turn in the same conversation; the original stays as version 1, and authored HTML stays inert')
 page.locator('.reply [data-action=version][data-step="-1"]').click();expect(page.locator('.reply .version-pager')).to_contain_text('1/2');expect(page.locator('.reply-content')).to_contain_text('180 seconds');expect(page.locator('.reply [data-action=version][data-step="1"]')).to_be_focused()
 page.keyboard.press('Enter');expect(page.locator('.reply .version-pager')).to_contain_text('2/2');expect(page.locator('.reply-content')).to_contain_text('revised');checks.append('the reply arrows switch between answer versions in place and keep the keyboard on the arrows')
 page.locator('.reasoning summary').click();expect(page.locator('.reasoning summary')).to_contain_text('Manually edited');expect(page.locator('.reasoning-content')).to_contain_text('local correction');checks.append('edited thinking is visibly labelled local-only')
 page.locator('[data-action=edit-thinking]').click();expect(page.locator('#inline-reasoning')).to_be_focused();page.locator('[data-action=inline-cancel]').click();expect(page.locator('.inline-editor')).to_have_count(0);checks.append('Edit thinking text opens the same editor at the thinking field; Cancel without changes closes it at once')
 page.locator('[data-action=edit-reply]').click();page.locator('#inline-content').fill('Unsaved text');page.evaluate('window.__changeReply()');page.locator('[data-action=inline-save]').click();expect(page.locator('#toast')).to_contain_text('changed');expect(page.locator('#inline-content')).to_have_value('Unsaved text')
 page.locator('[data-action=inline-cancel]').click();page.locator('[data-action=inline-discard]').click();expect(page.locator('.inline-editor')).to_have_count(0);checks.append('stale edits fail without overwriting either concurrent or unsaved text')
 page.locator('[data-action=edit-reply]').click();page.locator('#inline-content').fill('Edit of a reply that goes away');page.evaluate('window.__dropReply()');expect(page.locator('.inline-editor')).to_have_count(0);expect(page.locator('#toast')).to_contain_text('no longer shown')
 page.locator('[data-action=edit-reply]').click();expect(page.locator('.inline-editor')).to_be_visible();page.locator('[data-action=inline-cancel]').click();checks.append('an answer edit whose reply leaves the conversation closes with a notice, and another answer can be edited')
 page.locator('#prompt').fill('Draft before editing');page.locator('.user-row [data-action=edit]').click();expect(page.locator('#message-edit')).to_be_visible();expect(page.locator('#message-edit')).to_contain_text('Editing message 1')
 expect(page.locator('#prompt')).to_have_value(original['threads'][0]['turns'][0]['prompt']);expect(page.locator('#attachments')).to_contain_text('observations.csv')
 page.locator('[data-action=message-edit-cancel]').click();expect(page.locator('#message-edit')).to_be_hidden();expect(page.locator('#prompt')).to_have_value('Draft before editing');checks.append('Edit on a message puts it and its files in the composer; Cancel brings the draft back')
 page.locator('.user-row [data-action=edit]').click();page.locator('#prompt').fill('Revised user question\n第二行');page.locator('#send').click()
 expect(page.locator('#send')).to_be_enabled(timeout=20000);expect(page.locator('.user-prompt')).to_have_text('Revised user question\n第二行');expect(page.locator('#prompt')).to_have_value('Draft before editing');expect(page.locator('#message-edit')).to_be_hidden()
 w=page.evaluate('window.__inspect()');thread=w['threads'][0];assert len(w['threads'])==1 and len(thread['turns'])==1 and thread['turns'][0]['attachments'][0]['name']=='observations.csv' and thread['draft']=='Draft before editing',thread['draft']
 expect(page.locator('.user-row .version-pager')).to_contain_text('2/2');checks.append('Send makes a new version of the edited message with its files, answered in the same conversation, and the draft comes back')
 page.locator('.user-row [data-action=version][data-step="-1"]').click();expect(page.locator('.user-prompt')).to_contain_text('Explain the repair');expect(page.locator('.user-row .version-pager')).to_contain_text('1/2');expect(page.locator('.reply .version-pager')).to_contain_text('2/2');expect(page.locator('.reply-content')).to_contain_text('revised')
 checks.append('the message arrows switch between prompts, landing on the latest answer to each')
 page.locator('.reply [data-action=retry]').click();expect(page.locator('#send')).to_be_enabled(timeout=20000);expect(page.locator('.reply .version-pager')).to_contain_text('3/3');assert len(page.evaluate('window.__inspect().threads'))==1;checks.append('Retry asks again in the same conversation, as another version of the answer')
 expect(page.locator('#composer-role')).to_be_hidden();page.evaluate("()=>{const b=document.createElement('button');b.dataset.action='view';document.body.append(b);b.click();b.remove();}");page.locator('#view-roleMessages').check();page.keyboard.press('Escape')
 expect(page.locator('#composer-role')).to_be_visible();page.locator('#composer-role').select_option('system');expect(page.locator('#send')).to_contain_text('Add');page.locator('#prompt').fill('Answer tersely.');page.locator('#send').click()
 expect(page.locator('.role-turn .role-message')).to_have_text('Answer tersely.');expect(page.locator('.role-turn .message-label')).to_contain_text('System');w=page.evaluate('window.__inspect()');turn=w['threads'][0]['turns'][-1];assert turn['role']=='system' and turn['replies']==[]
 page.locator('#composer-role').select_option('user');checks.append('messages in other roles are off by default; turned on, the composer adds a system message without asking a model')
 turns=page.locator('.turn').count();page.locator('[data-action=edit-draft]').click();page.locator('#editor-content').fill('A long draft\n\n中文输入 with $y=2$.');page.locator('#editor-save').click();expect(page.locator('#prompt')).to_have_value('A long draft\n\n中文输入 with $y=2$.');expect(page.locator('.turn')).to_have_count(turns);checks.append('expanded composer saves multiline Unicode drafts without generating a reply')
 page.locator('[data-action=edit-draft]').click();page.locator('#editor-content').fill('Undo example');page.locator('#editor-content').select_text();page.locator('[data-editor=bold]').click();expect(page.locator('#editor-content')).to_have_value('**Undo example**');page.locator('#editor-content').press('Control+z');expect(page.locator('#editor-content')).to_have_value('Undo example');page.keyboard.press('Escape');page.locator('[data-editor=discard]').click();checks.append('formatting controls preserve native textarea undo')
 page.locator('[data-action=project-create]').click();page.locator('#project-name').fill('Workbench design');page.locator('#project-form button[type=submit]').click();expect(page.locator('#project-dialog')).to_be_hidden();project=page.evaluate('window.__inspect().projects[0]');expect(page.locator('.project-group')).to_contain_text('Workbench design');checks.append('projects can be created from navigation')
 page.locator('#project-breadcrumb').click();page.locator('#move-project').select_option(project['id']);page.locator('#move-form button[type=submit]').click();expect(page.locator('#project-breadcrumb')).to_have_text('Workbench design');assert page.locator('.project-group .thread.selected').count()==1;checks.append('moving a thread updates both its project group and breadcrumb')
 page.locator('[data-action=project-manage]').click();page.locator('#project-name').fill('Desktop client');page.locator('#project-form button[type=submit]').click();expect(page.locator('#project-breadcrumb')).to_have_text('Desktop client');checks.append('project rename updates the active thread header')
 page.locator('[data-action=project-manage]').click();page.locator('[data-action=project-remove]').click();expect(page.locator('#project-delete-confirm')).to_contain_text('not be deleted');before=len(page.evaluate('window.__inspect().threads'));page.locator('[data-action=project-confirm-remove]').click();expect(page.locator('#project-dialog')).to_be_hidden();assert len(page.evaluate('window.__inspect().threads'))==before;expect(page.locator('#project-breadcrumb')).to_have_text('Unfiled');checks.append('project removal requires confirmation and preserves all threads')
 page.evaluate('window.__seed()');page.evaluate('window.__busy(true)');page.locator('[data-action=edit-reply]').click();expect(page.locator('#toast')).to_contain_text('Stop');expect(page.locator('.inline-editor')).to_have_count(0);page.evaluate('window.__busy(false)');checks.append('editing an active thread is blocked before opening a stale editor')
 page.locator('#prompt').fill('IME draft');page.locator('#prompt').dispatch_event('keydown',{'key':'Enter','isComposing':True,'keyCode':229});assert len(page.evaluate('window.__inspect().threads.find(t=>t.id===window.__inspect().activeId).turns'))==1;checks.append('IME composition confirmation never submits a message')
 # Chromium lets a page prevent one close request per user activation, so a second Escape used to close the
 # editor and drop its text; the renderer now handles Escape itself. Nothing may query the page between the
 # two presses: Playwright evaluates with a user gesture, which would grant a new activation and hide the
 # defect. An Escape that ends an IME composition belongs to the IME.
 fresh=b.new_page(viewport={'width':1280,'height':900});fresh.on('pageerror',lambda e:errors.append(str(e)));fresh.set_content(html)
 fresh.locator('#prompt').fill('Draft');fresh.locator('[data-action=edit-draft]').click();fresh.locator('#editor-content').fill('Unsaved editor text')
 fresh.locator('#editor-content').dispatch_event('keydown',{'key':'Escape','isComposing':True,'keyCode':229});expect(fresh.locator('.editor-discard')).to_be_hidden();expect(fresh.locator('#edit-dialog')).to_be_visible()
 checks.append('an Escape that ends an IME composition is left to the IME')
 fresh.keyboard.press('Escape');fresh.keyboard.press('Escape');fresh.wait_for_timeout(150)
 expect(fresh.locator('#edit-dialog')).to_be_visible();expect(fresh.locator('.editor-discard')).to_be_visible();expect(fresh.locator('#editor-content')).to_have_value('Unsaved editor text');fresh.close()
 checks.append('a second Escape keeps the editor and its unsaved text behind the discard question')
 assert not errors;checks.append('editing and project flows produced no unhandled JavaScript errors')
 b.close()
result={'checks':len(checks),'passed':checks,'javascript_errors':errors,'scope':'Chromium renderer with synthetic fixtures; not native Windows or live provider'}
(root/'docs/ui-editing-checks.json').write_text(json.dumps(result,indent=2));print(json.dumps(result,indent=2))
