"""Production renderer + synthetic memory-only fixtures. No native/provider calls."""
import argparse,json
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
parser=argparse.ArgumentParser();parser.add_argument('--chromium',default=None);args=parser.parse_args()
root=Path(__file__).resolve().parents[1];html=(root/'preview/index.html').read_text(encoding='utf-8');checks=[];errors=[]
marker='const pause = ms => new Promise(r => setTimeout(r, ms));'
fixture=r'''window.__inspect=()=>structuredClone(workspace);
window.__seed=()=>{const t=workspace.threads.find(t=>t.id===workspace.activeId);t.title='Repair analysis';t.turns=[{id:'test-turn',prompt:'Explain the repair measurements. 中文输入。',attachments:[{name:'observations.csv',content:'142,180,218'}],createdAt:Date.now(),selectedReplyId:'test-reply',replies:[{id:'test-reply',model:'demo/writer',content:'The sample mean is **180 seconds**.\n\n$$x = 180$$\n\nThis is synthetic demonstration text.',reasoning:'Synthetic returned thinking: separate the arithmetic from the scheduling assumption.',status:'complete',finishReason:'stop',error:null,usage:null,elapsedMs:1234,tools:[],toolMessages:[]}]}];emit();};
window.__changeReply=()=>{workspace.threads.find(t=>t.id===workspace.activeId).turns[0].replies[0].content+=' A concurrent update.';emit();};
window.__busy=value=>{busy=value?workspace.activeId:null;emit();};
'''
assert marker in html;html=html.replace(marker,marker+fixture,1)
with sync_playwright() as p:
 b=p.chromium.launch(executable_path=args.chromium,headless=True,args=['--no-sandbox']);page=b.new_page(viewport={'width':1440,'height':1000});page.on('pageerror',lambda e:errors.append(str(e)))
 page.set_content(html);page.evaluate('window.__seed()');original=page.evaluate('window.__inspect()')
 expect(page.locator('.nav-section-heading h2').first).to_have_text('Projects');expect(page.locator('#thread-title')).to_have_text('Repair analysis');checks.append('project and thread headings expose a real active thread title')
 page.locator('[data-action=edit-reply]').click();expect(page.locator('#edit-dialog')).to_be_visible()
 value='A revised **answer** with $x=216$.\n\n<script>window.injected=true</script>'
 page.locator('#editor-content').fill(value);page.locator('[data-editor-mode=preview]').click();expect(page.locator('#editor-preview math')).to_have_count(1);assert not page.evaluate('Boolean(window.injected)');checks.append('answer editor previews Markdown/LaTeX while authored HTML stays inert')
 page.locator('[data-editor-mode=changes]').click();expect(page.locator('.diff-added')).to_contain_text('revised');expect(page.locator('.diff-removed')).to_contain_text('180');checks.append('bounded Changes view shows the edited region')
 page.locator('[data-editor-field=reasoning]').click();page.locator('[data-editor-mode=write]').click();page.locator('#editor-reasoning').fill('My local correction, not new model output.');page.locator('[data-editor-field=content]').click();expect(page.locator('#editor-content')).to_have_value(value);checks.append('answer and thinking buffers survive tab switches')
 page.keyboard.press('Escape');expect(page.locator('.editor-discard')).to_be_visible();expect(page.locator('#edit-dialog')).to_be_visible();page.locator('[data-editor=keep]').click();checks.append('Escape offers a discard guard without losing changes')
 page.locator('#editor-content').press('Control+Enter');expect(page.locator('#edit-dialog')).to_be_hidden();w=page.evaluate('window.__inspect()');assert len(w['threads'])==2;assert w['threads'][1]['turns']==original['threads'][0]['turns'];expect(page.locator('.edited-label')).to_be_visible();expect(page.locator('#branch-origin')).to_be_visible();checks.append('save creates a new selected branch with explicit edit provenance and an untouched original')
 page.locator('.reasoning summary').click();expect(page.locator('.reasoning summary')).to_contain_text('Manually edited');expect(page.locator('.reasoning-content')).to_contain_text('local correction');checks.append('edited thinking is visibly labelled local-only')
 page.locator('[data-action=edit-thinking]').click();expect(page.locator('#editor-reasoning')).to_be_visible();page.locator('[data-editor=reset]').click();expect(page.locator('#editor-reasoning')).to_have_value(original['threads'][0]['turns'][0]['replies'][0]['reasoning']);page.locator('[data-editor=save]').click();expect(page.locator('#edit-dialog')).to_be_hidden();checks.append('thinking has a direct editor action and original-text restoration')
 page.locator('[data-action=edit-reply]').click();page.locator('#editor-content').fill('Unsaved text');page.evaluate('window.__changeReply()');page.locator('[data-editor=save]').click();expect(page.locator('#toast')).to_contain_text('changed');expect(page.locator('#editor-content')).to_have_value('Unsaved text');expect(page.locator('#edit-dialog')).to_be_visible();page.keyboard.press('Escape');page.locator('[data-editor=discard]').click();checks.append('stale edits fail without overwriting either concurrent or unsaved text')
 page.locator('[data-action=edit]').click();expect(page.locator('#editor-attachments')).to_contain_text('observations.csv');page.locator('#editor-content').fill('Revised user question\n第二行');before=len(page.evaluate('window.__inspect().threads'));page.locator('#editor-save').click();expect(page.locator('#edit-dialog')).to_be_hidden();expect(page.locator('#prompt')).to_have_value('Revised user question\n第二行');expect(page.locator('#attachments')).to_contain_text('observations.csv');expect(page.locator('.turn')).to_have_count(0);assert len(page.evaluate('window.__inspect().threads'))==before+1;checks.append('prompt editing creates an unsent branch draft with its attachments')
 page.locator('[data-action=edit-draft]').click();page.locator('#editor-content').fill('A long draft\n\n中文输入 with $y=2$.');page.locator('#editor-save').click();expect(page.locator('#prompt')).to_have_value('A long draft\n\n中文输入 with $y=2$.');expect(page.locator('.turn')).to_have_count(0);checks.append('expanded composer saves multiline Unicode drafts without generating a reply')
 page.locator('[data-action=edit-draft]').click();page.locator('#editor-content').fill('Undo example');page.locator('#editor-content').select_text();page.locator('[data-editor=bold]').click();expect(page.locator('#editor-content')).to_have_value('**Undo example**');page.locator('#editor-content').press('Control+z');expect(page.locator('#editor-content')).to_have_value('Undo example');page.keyboard.press('Escape');page.locator('[data-editor=discard]').click();checks.append('formatting controls preserve native textarea undo')
 page.locator('[data-action=project-create]').click();page.locator('#project-name').fill('Workbench design');page.locator('#project-form button[type=submit]').click();expect(page.locator('#project-dialog')).to_be_hidden();project=page.evaluate('window.__inspect().projects[0]');expect(page.locator('.project-group')).to_contain_text('Workbench design');checks.append('projects can be created from navigation')
 page.locator('#project-breadcrumb').click();page.locator('#move-project').select_option(project['id']);page.locator('#move-form button[type=submit]').click();expect(page.locator('#project-breadcrumb')).to_have_text('Workbench design');assert page.locator('.project-group .thread.selected').count()==1;checks.append('moving a thread updates both its project group and breadcrumb')
 page.locator('[data-action=project-manage]').click();page.locator('#project-name').fill('Desktop client');page.locator('#project-form button[type=submit]').click();expect(page.locator('#project-breadcrumb')).to_have_text('Desktop client');checks.append('project rename updates the active thread header')
 page.locator('[data-action=project-manage]').click();page.locator('[data-action=project-remove]').click();expect(page.locator('#project-delete-confirm')).to_contain_text('not be deleted');before=len(page.evaluate('window.__inspect().threads'));page.locator('[data-action=project-confirm-remove]').click();expect(page.locator('#project-dialog')).to_be_hidden();assert len(page.evaluate('window.__inspect().threads'))==before;expect(page.locator('#project-breadcrumb')).to_have_text('Unfiled');checks.append('project removal requires confirmation and preserves all threads')
 page.evaluate('window.__seed()');page.evaluate('window.__busy(true)');page.locator('[data-action=edit-reply]').click();expect(page.locator('#toast')).to_contain_text('Stop');expect(page.locator('#edit-dialog')).to_be_hidden();page.evaluate('window.__busy(false)');checks.append('editing an active thread is blocked before opening a stale editor')
 page.locator('#prompt').fill('IME draft');page.locator('#prompt').dispatch_event('keydown',{'key':'Enter','isComposing':True,'keyCode':229});assert len(page.evaluate('window.__inspect().threads.find(t=>t.id===window.__inspect().activeId).turns'))==1;checks.append('IME composition confirmation never submits a message')
 # Chromium lets a page prevent one close request per user activation, so a second Escape used to close the
 # editor and drop its text; the renderer now handles Escape itself. Nothing may query the page between the
 # two presses: Playwright evaluates with a user gesture, which would grant a new activation and hide the
 # defect. An Escape that ends an IME composition belongs to the IME.
 fresh=b.new_page(viewport={'width':1280,'height':900});fresh.on('pageerror',lambda e:errors.append(str(e)));fresh.set_content(html)
 fresh.locator('#prompt').fill('Draft');fresh.locator('[data-action=edit-draft]').click();fresh.locator('#editor-content').fill('Unsaved editor text')
 fresh.locator('#editor-content').dispatch_event('keydown',{'key':'Escape','isComposing':True,'keyCode':229});expect(fresh.locator('.editor-discard')).to_be_hidden();expect(fresh.locator('#edit-dialog')).to_be_visible()
 checks.append('an Escape that ends an IME composition is left to the IME')
 fresh.keyboard.press('Escape');fresh.keyboard.press('Escape');fresh.wait_for_timeout(150)
 expect(fresh.locator('#edit-dialog')).to_be_visible();expect(fresh.locator('.editor-discard')).to_be_visible();expect(fresh.locator('#editor-content')).to_have_value('Unsaved editor text');fresh.close()
 checks.append('a second Escape keeps the editor and its unsaved text behind the discard question')
 assert not errors;checks.append('editing and project flows produced no unhandled JavaScript errors')
 b.close()
result={'checks':len(checks),'passed':checks,'javascript_errors':errors,'scope':'Chromium renderer with synthetic fixtures; not native Windows or live provider'}
(root/'docs/ui-editing-checks.json').write_text(json.dumps(result,indent=2));print(json.dumps(result,indent=2))
