import test from 'node:test';
import assert from 'node:assert/strict';
import { capabilityFor, normalizeCapability, reasoningParameters } from '../dist/core/capabilities.js';
import { chartSpec,chartSVG,tableSpec,tableHTML,diagramSpec,diagramSVG,VISUAL_TOOLS } from '../dist/core/visual-tools.js';
import { validateWorkspace,validateArtifact,settings } from '../dist/core/validation.js';
import { newWorkspace,beginTurn,exportThread,importThread,chooseReply,forkThread } from '../dist/core/workspace.js';
import { executeVisual } from '../desktop/visual-runtime.mjs';
import { loadModelCapabilities } from '../desktop/model-catalog.mjs';
import { printableDocument } from '../dist/core/pdf-document.js';
const chart={title:'Demo',type:'line',labels:['a','b','c'],series:[{name:'series',values:[1,null,3]}]};
const live = (overrides = {}) => normalizeCapability({
  modelName: 'fixture',
  chatConfig: { reasoningConfig: {
    supportsEffort: true, supportsToggle: true,
    effortMap: { low: 'high', medium: 'high', high: 'max' },
    params: { '/v1/chat/completions': {
      enable: { thinking: { type: 'enabled' }, reasoning_effort: '$EFFORT' },
      disable: { thinking: { type: 'disabled' } },
    } },
    ...overrides,
  } },
});

test('new visual tools are actual function schemas with distinct registered names',()=>{assert.equal(VISUAL_TOOLS.length,6);assert.equal(new Set(VISUAL_TOOLS.map(t=>t.function.name)).size,6);for(const t of VISUAL_TOOLS){assert.equal(t.type,'function');assert.equal(t.function.parameters.additionalProperties,false);}});
test('Tinfoil effort mapping exposes unique actual wire levels',()=>{const cap=live();assert.deepEqual(cap.effort,['high','max']);assert.deepEqual(reasoningParameters(cap,'max'),{thinking:{type:'enabled'},reasoning_effort:'max'});});
test('provider default omits all reasoning parameters',()=>{assert.deepEqual(reasoningParameters(live(),'default'),{});});
test('thinking toggle is independent of effort visibility',()=>{const cap=live();assert.deepEqual(reasoningParameters(cap,'max','disabled'),{thinking:{type:'disabled'}});assert.deepEqual(reasoningParameters(cap,'default','enabled'),{thinking:{type:'enabled'}});});
test('unsupported effort is omitted rather than silently mapped',()=>{assert.deepEqual(reasoningParameters(live(),'low'),{});});
test('Kimi K3 bundled profile has fixed effort and no guessed toggle',()=>{const cap=capabilityFor('kimi-k3');assert.equal(cap.source,'bundled');assert.deepEqual(cap.effort,[]);assert.deepEqual(reasoningParameters(cap,'max','enabled'),{});});
test('DeepSeek V4 fallback is narrow and provider-specific',()=>{assert.deepEqual(capabilityFor('deepseek-v4-pro').effort,['high','max']);assert.deepEqual(capabilityFor('deepseek-v3.2').effort,[]);assert.deepEqual(capabilityFor('deepseek-v9').effort,[]);});
test('live known metadata overrides bundled assumptions',()=>{const fixed=normalizeCapability({modelName:'deepseek-v4-pro',chatConfig:{reasoningConfig:{}}});assert.deepEqual(capabilityFor('deepseek-v4-pro',[fixed]).effort,[]);});
test('unknown model gets no effort or on/off parameters',()=>{assert.deepEqual(reasoningParameters(capabilityFor('mystery'),'high','enabled'),{});});
test('catalog reasoning data cannot override credentials, endpoints, messages or tools',()=>{const cap=normalizeCapability({id:'m',chatConfig:{reasoningConfig:{supportsEffort:true,params:{'/v1/chat/completions':{enable:{model:'evil',messages:[],tools:[],baseURL:'https://evil',apiKey:'secret',headers:{Authorization:'secret'},reasoning_effort:'$EFFORT'}}}}}});assert.deepEqual(reasoningParameters(cap,'high'),{reasoning_effort:'high'});});
test('prototype keys in metadata cannot pollute object prototypes',()=>{const c=normalizeCapability(JSON.parse('{"id":"x","chatConfig":{"reasoningConfig":{"supportsEffort":true,"params":{"/v1/chat/completions":{"enable":{"thinking":{"__proto__":{"polluted":true}},"reasoning_effort":"$EFFORT"}}}}}}'));assert.equal({}.polluted,undefined);assert.ok(!JSON.stringify(reasoningParameters(c,'high')).includes('__proto__'));});
test('chart validates matching finite values and bounded arrays',()=>{for(const patch of [{labels:[]},{series:[{name:'x',values:[1]}]},{series:[{name:'x',values:[Infinity,2,3]}]},{labels:Array(201).fill('x')},{x_values:[1]}])assert.throws(()=>chartSpec({...chart,...patch}));});
test('chart gaps stay gaps and negative bars retain a zero baseline',()=>{const svg=chartSVG(chartSpec(chart));assert.equal((svg.match(/<polyline/g)||[]).length,2);const bar=chartSVG(chartSpec({...chart,type:'bar',series:[{name:'negative',values:[-3,0,4]}]}));assert.ok(!/NaN|Infinity/.test(bar));assert.match(bar,/<rect/);});
test('all-hidden and single-point chart states remain finite',()=>{assert.ok(!/NaN|Infinity/.test(chartSVG(chartSpec(chart),[0])));assert.ok(!/NaN|Infinity/.test(chartSVG(chartSpec({...chart,labels:['x'],series:[{name:'x',values:[3]}]}))));});
test('visual labels are escaped, not HTML or JavaScript',()=>{const svg=chartSVG(chartSpec({...chart,title:'<script>alert(1)</script>',labels:['<img onerror=x>','x','y']}));assert.ok(!svg.includes('<script>'));assert.ok(!svg.includes('<img '));assert.match(svg,/&lt;script&gt;/);});
test('table validates dimensionality, cell values and row budgets',()=>{const base={title:'table',columns:['a'],rows:[[1],[true],[null]]};assert.equal(tableSpec(base).rows.length,3);for(const p of [{columns:[]},{rows:[[1,2]]},{rows:[[{}]]},{rows:Array(501).fill([1])}])assert.throws(()=>tableSpec({...base,...p}));});
test('table HTML renders data inertly',()=>{assert.ok(!tableHTML(tableSpec({title:'x',columns:['<script>'],rows:[['<img src=x>']]})).includes('<img'));});
test('diagram rejects missing edge endpoints, duplicate nodes and overlapping positions',()=>{const base={title:'flow',nodes:[{id:'a',label:'a'}],edges:[]};assert.match(diagramSVG(diagramSpec(base)),/<svg/);for(const patch of [{edges:[{from:'a',to:'missing'}]},{nodes:[{id:'a',label:'a'},{id:'a',label:'b'}]},{nodes:[{id:'a',label:'a',column:0,row:0},{id:'b',label:'b',column:0,row:0}]}])assert.throws(()=>diagramSpec({...base,...patch}));});
test('artifact creation returns an ID and preserves complete source without running code',async()=>{const source='<script>throw new Error("DO NOT RUN")</script>';const result=await executeVisual('create_artifact',JSON.stringify({title:'demo',kind:'html',source}));assert.equal(result.artifacts[0].source,source);assert.equal(result.output.artifact_id,result.artifacts[0].id);});
test('revision creates a new artifact and preserves the parent',async()=>{const original=(await executeVisual('create_artifact',JSON.stringify({title:'draft',kind:'text',source:'one'}))).artifacts[0];const revision=(await executeVisual('update_artifact',JSON.stringify({artifact_id:original.id,source:'two'}),{artifacts:[original]})).artifacts[0];assert.equal(original.source,'one');assert.equal(revision.source,'two');assert.equal(revision.rootId,original.id);assert.equal(revision.parentId,original.id);assert.equal(revision.version,2);});
test('revising a historical revision increments the conversation-wide version',async()=>{const a=(await executeVisual('create_artifact',JSON.stringify({title:'d',kind:'text',source:'1'}))).artifacts[0];const b=(await executeVisual('update_artifact',JSON.stringify({artifact_id:a.id,source:'2'}),{artifacts:[a]})).artifacts[0];const c=(await executeVisual('update_artifact',JSON.stringify({artifact_id:a.id,source:'branch'}),{artifacts:[a,b]})).artifacts[0];assert.equal(c.version,3);assert.equal(c.parentId,a.id);});
test('artifact source reading is bounded and does not claim pixel inspection',async()=>{const a=(await executeVisual('create_artifact',JSON.stringify({title:'large',kind:'text',source:'x'.repeat(20000)}))).artifacts[0];const read=await executeVisual('read_artifact',JSON.stringify({artifact_id:a.id}),{artifacts:[a]});assert.equal(read.output.source.length,16000);assert.equal(read.output.truncated,true);assert.match(read.output.note,/No rendered-pixel/);});
test('artifact retrieval cannot access missing or arbitrary paths',async()=>{await assert.rejects(executeVisual('read_artifact','{"artifact_id":"../secret"}'));await assert.rejects(executeVisual('read_artifact','{"artifact_id":"missing"}'));});
test('typed artifact metadata round-trips through encrypted-workspace validation',async()=>{const w=newWorkspace();w.threads[0].settings.model='fixture';beginTurn(w.threads[0],'x',[]);const r=w.threads[0].turns[0].replies[0];r.status='complete';const a=(await executeVisual('render_chart',JSON.stringify(chart))).artifacts[0];r.tools=[{id:'tool',callId:'call',name:'render_chart',arguments:JSON.stringify(chart),origin:'model',status:'complete',stdout:'',stderr:'',exitCode:0,elapsedMs:0,artifacts:[a],truncated:false}];assert.deepEqual(validateWorkspace(w).threads[0].turns[0].replies[0].tools[0].artifacts[0],a);const imported=importThread(w,JSON.parse(exportThread(w.threads[0])));assert.equal(imported.turns[0].replies[0].tools[0].artifacts[0].id,a.id);});
test('PDF tool uses injected rendering and validates bytes',async()=>{let input;const result=await executeVisual('create_artifact',JSON.stringify({title:'report',kind:'pdf',source:'<h1>Report</h1>'}),{pdfRenderer:async v=>{input=v.html;return Buffer.from('%PDF-1.7\nfixture');}});assert.equal(input,'<h1>Report</h1>');assert.equal(result.artifacts[0].mime,'application/pdf');await assert.rejects(executeVisual('create_artifact','{"title":"x","kind":"pdf","source":"x"}'),/requires/);await assert.rejects(executeVisual('create_artifact','{"title":"x","kind":"pdf","source":"x"}',{pdfRenderer:async()=>Buffer.from('not pdf')}),/valid/);});
test('PDF print document starts with restrictive CSP before any model source',()=>{const s=printableDocument('<script>bad()</script><img src="https://example.com">');assert.ok(s.indexOf('script-src')<s.indexOf('bad()'));assert.match(s,/frame-src 'none'/);assert.throws(()=>printableDocument('x'.repeat(120001)));});
test('artifact cancellation is honored before work begins',async()=>{const c=new AbortController();c.abort();await assert.rejects(executeVisual('render_chart',JSON.stringify(chart),{signal:c.signal}),/cancelled/);});
test('catalog request uses a fixed public endpoint without authorization',async()=>{let called;const caps=await loadModelCapabilities(async(url,options)=>{called={url,options};return new Response(JSON.stringify([{id:'m',chatConfig:{reasoningConfig:{supportsEffort:true}}}]),{status:200});});assert.equal(called.url,'https://api.tinfoil.sh/api/config/models');assert.equal(called.options.headers.Authorization,undefined);assert.equal(called.options.redirect,'error');assert.equal(caps.length,1);});
test('oversized or malformed public catalogs fail closed',async()=>{await assert.rejects(loadModelCapabilities(async()=>new Response('{}')));await assert.rejects(loadModelCapabilities(async()=>new Response('x'.repeat(2*1024*1024+1))));});
test('old settings migrate without silently enabling visualization tools',()=>{const w=newWorkspace();const old={...w.threads[0].settings};delete old.visualTools;delete old.thinkingMode;assert.equal(settings(old).visualTools,false);assert.equal(settings(old).thinkingMode,'default');assert.equal(w.threads[0].settings.visualTools,true);});

function compareFixture(){const w=newWorkspace(),t=w.threads[0];Object.assign(t.settings,{model:'deepseek-v4-pro',reasoningEffort:'max',compare:true,compareModel:'kimi-k3'});beginTurn(t,'Compare',[]);t.turns[0].replies.forEach(r=>r.status='complete');return{w,t,turn:t.turns[0],reply:t.turns[0].replies[1]};}
test('selecting a different-model comparison answer resets stale effort',()=>{const {t,turn,reply}=compareFixture();chooseReply(t,turn.id,reply.id);assert.equal(t.settings.model,'kimi-k3');assert.equal(t.settings.reasoningEffort,'default');});
test('branching into a different model resets stale effort',()=>{const {w,t,turn,reply}=compareFixture();const branch=forkThread(w,t.id,turn.id,false,reply.id);assert.equal(branch.settings.model,'kimi-k3');assert.equal(branch.settings.reasoningEffort,'default');assert.equal(t.settings.reasoningEffort,'max');});
