import type { Snapshot } from '../core/types.js';
import { signedOutAccount, initials } from '../core/account.js';
import { escapeHtml as e } from '../core/markdown.js';
const date=(value:number|null):string=>value===null?'Not reported':new Date(value).toLocaleString();
const number=(value:number|null):string=>value===null?'Not reported':value.toLocaleString();
export function accountFooter(snapshot:Snapshot):string {
  if(snapshot.platform==='android'&&!snapshot.chatAvailable)return `<span class="account-avatar" aria-hidden="true">○</span><span class="account-footer-text"><strong>Account</strong><small>${snapshot.hasKey?'Developer API key':'Add an API key'}</small></span>`;
  const a=snapshot.account??signedOutAccount();
  return `<span class="account-avatar" aria-hidden="true">${a.profile?e(initials(a.profile.name)):'○'}</span><span class="account-footer-text"><strong>${e(a.profile?.name??'Account')}</strong><small>${a.status==='signed-in'?'Tinfoil Chat':a.status==='signing-in'?'Signing in…':a.status==='restoring'?'Restoring sign-in…':a.status==='expired'?'Reconnect account':'Sign in or manage access'}</small></span>`;
}
/** Tinfoil cloud chats (docs/CLOUD.md): the chat key, the sync state and its actions. The key is typed or opened here and
 * handed to the host once; snapshots never contain it. */
function cloudSection(s:Snapshot):string {
  const c=s.cloud;if(s.platform==='android'||!c)return '';
  const signedIn=s.account?.status==='signed-in',busy=c.state==='syncing'||c.state==='checking';
  if(c.state==='off'||!c.keyId)return `<section class="account-section cloud-section"><h3>Tinfoil cloud chats</h3><p>Add your chat key to see your Tinfoil Chat cloud chats and projects here. Continuing, renaming or deleting one of them in Workbench changes it in your Tinfoil account too. Conversations that exist only here stay local unless you move one to the cloud.</p>${signedIn?`<label class="cloud-key-label" for="cloud-key">Chat key</label><input id="cloud-key" type="password" autocomplete="off" spellcheck="false" placeholder="key_…" ${busy?'disabled':''}><div class="account-actions"><button class="primary" data-action="cloud-connect" ${busy?'disabled':''}>${busy?'Checking…':'Connect'}</button><button data-action="cloud-key-file" ${busy?'disabled':''}>Open key file…</button></div>${c.message?`<p class="account-message" role="status">${e(c.message)}</p>`:''}<p class="muted">The key is in Tinfoil Chat under Settings → Cloud sync. Workbench keeps it encrypted on this PC.</p>`:'<p class="muted">Sign in to Tinfoil Chat first.</p>'}</section>`;
  const when=c.lastSyncAt?new Date(c.lastSyncAt).toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'}):null;
  const label=busy?'Syncing…':c.state==='error'?'Sync stopped':when?`Synced at ${when}`:'Connected';
  return `<section class="account-section cloud-section"><h3>Tinfoil cloud chats</h3><p class="cloud-state" role="status" data-state="${e(c.state)}">${label} · ${c.chats} ${c.chats===1?'chat':'chats'} · ${c.projects} ${c.projects===1?'project':'projects'}</p>${c.message?`<p class="account-message">${e(c.message)}</p>`:''}${c.older?'<p class="muted">Only your 300 most recent cloud chats are shown here.</p>':''}${signedIn?'':'<p class="muted">Sign in to Tinfoil Chat to sync.</p>'}<div class="account-actions"><button data-action="cloud-sync" ${busy||!signedIn?'disabled':''}>Sync now</button><button data-action="cloud-disconnect" ${busy?'disabled':''}>Remove chat key…</button></div><p class="muted">Key ID ${e(c.keyId.slice(0,8))}…</p></section>`;
}
export function accountOverview(s:Snapshot):string {
  // Without a WebView that can isolate Tinfoil's sign-in page, the Android app connects with a developer API key.
  if(s.platform==='android'&&!s.chatAvailable)return `<section class="account-identity"><span class="account-avatar large" aria-hidden="true">○</span><div><h3>Developer API key</h3><p>${s.hasKey?'A key is saved in this device’s encrypted workspace.':'No API key is saved yet.'}</p></div></section>
    <section class="account-section"><h3>Connection for new requests</h3><p>The Android app connects with a separate developer API key here. Tinfoil Chat sign-in needs a newer Android System WebView on this device.</p><button data-action="account-api">${s.hasKey?'Manage saved API key':'Add an API key'}</button></section>`;
  const android=s.platform==='android',a=s.account??signedOutAccount(),p=a.profile,waiting=a.status==='signing-in',restoring=a.status==='restoring',busy=!!s.busyThreadId||s.verification.state==='checking',chat=s.connectionMode==='chat-account',usable=a.status==='signed-in';
  const active=chat?'Tinfoil Chat account':'Developer API key';
  return `${s.storage==='preview'?'<p class="account-demo-note">Offline preview · synthetic account data only. No credentials are accepted. <button data-action="account-sample">Toggle sample profile</button></p>':''}
    <section class="account-identity"><span class="account-avatar large" aria-hidden="true">${p?e(initials(p.name)):'○'}</span><div><h3>${e(p?.name??'Your Tinfoil account')}</h3><p>${e(p?.email??'Connect your existing Chat subscription.')}${p?.emailVerified?'<span class="account-verified">Verified email</span>':''}</p><span class="account-state" data-state="${a.status}" role="status">${waiting?'Opening Tinfoil sign-in…':restoring?'Restoring your saved sign-in…':usable?'Signed in':a.status==='expired'?'Session needs attention':a.status==='error'?'Sign-in incomplete':'Not signed in'}</span></div></section>
    ${a.message?`<p class="account-message" role="status">${e(a.message)}</p>`:''}
    <div class="account-actions">${waiting?'<button data-action="account-cancel">Cancel sign-in</button>':restoring?'':usable?`<button data-action="account-manage" ${busy?'disabled':''}>Manage profile & security</button><button data-action="account-refresh" ${busy?'disabled':''}>Refresh account</button><button data-action="account-signout" class="danger">Sign out…</button>`:`<button class="primary" data-action="account-login" ${busy?'disabled':''}>${p?'Reconnect Tinfoil Chat':'Sign in to Tinfoil Chat'}</button>${p?'<button data-action="account-signout">Sign out…</button>':''}`}</div>
    <section class="account-section"><h3>Connection for new requests</h3><div class="account-modes" role="group" aria-label="Connection mode"><button data-action="account-mode-chat" aria-pressed="${chat}" ${busy||waiting||restoring?'disabled':''}><strong>Tinfoil Chat</strong><span>Your signed-in subscription</span></button><button data-action="account-mode-api" aria-pressed="${!chat}" ${busy||waiting||restoring?'disabled':''}><strong>API key</strong><span>Separate developer access</span></button></div><p>Selected: <strong>${active}</strong>. No automatic fallback between billing modes.</p>${!chat?`<button data-action="account-api">${s.hasKey?'Manage saved API key':'Add an API key'}</button>`:usable&&a.entitlement==='active'?`<button data-action="account-connect" ${busy?'disabled':''}>Verify enclave & load models</button>`:''}</section>
    ${cloudSection(s)}
    ${p?`<details class="account-section account-details" data-key="account-usage"><summary>Subscription & usage</summary><dl class="account-facts"><div><dt>Chat access</dt><dd>${a.entitlement==='active'?'Token issued by Tinfoil':a.entitlement==='subscription-required'?'Subscription required':a.entitlement==='rate-limited'?'Usage limit reached':'Not checked'}</dd></div><div><dt>Subscription status</dt><dd>${e(p.subscriptionStatus??'Not reported')}</dd></div><div><dt>Subscription expiry</dt><dd>${date(p.subscriptionExpiresAt)}</dd></div><div><dt>Last access check</dt><dd>${date(a.checkedAt)}</dd></div></dl>${a.usage?`<div class="account-usage">${[['Input tokens',a.usage.inputTokens],['Output tokens',a.usage.outputTokens]].map(([label,v])=>{const b=v as import('../core/account.js').TokenBudget|null;return b?`<div class="account-budget"><div><strong>${label}</strong><span>${number(b.remaining)} remaining / ${number(b.max)}</span></div><progress max="${Math.max(1,b.max)}" value="${Math.min(b.max,b.used)}" aria-label="${label} used"></progress></div>`:'';}).join('')}${a.usage.remaining!==null?`<p>${number(a.usage.remaining)} requests remaining${a.usage.maxRequests!==null?' / '+number(a.usage.maxRequests):''}.</p>`:''}<p>Reported reset: ${date(a.usage.resetsAt)}</p></div>`:'<p>Tinfoil has not reported a usage budget for this session.</p>'}<p class="muted">Server-reported snapshots, not a live billing meter. Refresh to check again.</p></details>`:''}
    <details class="account-section account-details" data-key="account-session"><summary>Session & local workspace</summary>${android?`<p>Sign-in opens Tinfoil’s own sign-in page on a separate screen with its own website storage. Use your email and password; Google and Apple sign-in are not available in the Android app. Profile, password and security changes are handled on Tinfoil’s page.</p><p>While you are signed in, the website session is kept in the app’s private storage and account tokens stay in memory. Chat access renews automatically while the website session lasts. The stored session is deleted when the app next starts, so sign in again after reopening it. Workbench does not import cookies from your regular browser.</p>`:`<p>Sign-in opens Tinfoil’s own sign-in page in a separate, sandboxed window. Profile, password and security changes are handled there.</p>${s.rememberAccount!==false?'<p>While you are signed in, Workbench saves Tinfoil’s website session on this PC, encrypted with your Windows account, so you stay signed in after restarts and updates. Account tokens stay in memory, and Chat access renews automatically while the website session lasts. Signing out ends the session and deletes it from this PC.</p>':'<p>The website session and account tokens stay in memory until you sign out or quit. Chat access renews automatically while the website session lasts; after reopening the app, sign in again.</p>'}<p>Workbench does not import cookies from your regular browser.</p><button type="button" class="account-remember" role="switch" aria-checked="${s.rememberAccount!==false}" data-action="account-remember" ${waiting||restoring?'disabled':''}>Stay signed in on this PC</button>`}<p>Local conversations stay in this device’s encrypted workspace; signing in does not move them to the account. ${android?'':'Cloud chats appear only after you add your chat key under Tinfoil cloud chats. '}Existing history requires approval before using another connection.</p><p>This uses Tinfoil’s website session, not a registered app sign-in. ${android?'Android account access has been tested on one phone; additional sign-in methods require separate validation.':'Windows account access has been tested; additional sign-in methods require separate validation.'} No provider-private OAuth endpoint is assumed.</p>${p?`<dl class="account-facts"><div><dt>Account ID</dt><dd>${e(p.id)}</dd></div><div><dt>Inference token expiry</dt><dd>${date(a.tokenExpiresAt)}</dd></div></dl>`:''}</details>`;
}
