import type { Snapshot } from '../core/types.js';
import { signedOutAccount, initials } from '../core/account.js';
import { escapeHtml as e } from '../core/markdown.js';
const date=(value:number|null):string=>value===null?'Not reported':new Date(value).toLocaleString();
const number=(value:number|null):string=>value===null?'Not reported':value.toLocaleString();
export function accountFooter(snapshot:Snapshot):string {
  if(snapshot.platform==='android'&&!snapshot.chatAvailable)return `<span class="account-avatar" aria-hidden="true">○</span><span class="account-footer-text"><strong>Account</strong><small>${snapshot.hasKey?'Developer API key':'Add an API key'}</small></span>`;
  const a=snapshot.account??signedOutAccount();
  return `<span class="account-avatar" aria-hidden="true">${a.profile?e(initials(a.profile.name)):'○'}</span><span class="account-footer-text"><strong>${e(a.profile?.name??'Account')}</strong><small>${a.status==='signed-in'?'Tinfoil Chat':a.status==='signing-in'?'Signing in…':a.status==='expired'?'Reconnect account':'Sign in or manage access'}</small></span>`;
}
export function accountOverview(s:Snapshot):string {
  // Without a WebView that can isolate Tinfoil's sign-in page, the Android app connects with a developer API key.
  if(s.platform==='android'&&!s.chatAvailable)return `<section class="account-identity"><span class="account-avatar large" aria-hidden="true">○</span><div><h3>Developer API key</h3><p>${s.hasKey?'A key is saved in this device’s encrypted workspace.':'No API key is saved yet.'}</p></div></section>
    <section class="account-section"><h3>Connection for new requests</h3><p>The Android app connects with a separate developer API key here. Tinfoil Chat sign-in needs a newer Android System WebView on this device.</p><button data-action="account-api">${s.hasKey?'Manage saved API key':'Add an API key'}</button></section>
    <p class="account-optional">Custom system instructions are optional—not required. Leave them blank to use provider defaults.</p>`;
  const android=s.platform==='android',a=s.account??signedOutAccount(),p=a.profile,waiting=a.status==='signing-in',busy=!!s.busyThreadId||s.verification.state==='checking',chat=s.connectionMode==='chat-account',usable=a.status==='signed-in';
  const active=chat?'Tinfoil Chat account':'Developer API key';
  return `${s.storage==='preview'?'<p class="account-demo-note">Offline preview · synthetic account data only. No credentials are accepted. <button data-action="account-sample">Toggle sample profile</button></p>':''}
    <section class="account-identity"><span class="account-avatar large" aria-hidden="true">${p?e(initials(p.name)):'○'}</span><div><h3>${e(p?.name??'Your Tinfoil account')}</h3><p>${e(p?.email??'Connect your existing Chat subscription.')}${p?.emailVerified?'<span class="account-verified">Verified email</span>':''}</p><span class="account-state" data-state="${a.status}" role="status">${waiting?'Opening Tinfoil sign-in…':usable?'Signed in':a.status==='expired'?'Session needs attention':a.status==='error'?'Sign-in incomplete':'Not signed in'}</span></div></section>
    ${a.message?`<p class="account-message" role="status">${e(a.message)}</p>`:''}
    <div class="account-actions">${waiting?'<button data-action="account-cancel">Cancel sign-in</button>':usable?`<button data-action="account-manage" ${busy?'disabled':''}>Manage profile & security</button><button data-action="account-refresh" ${busy?'disabled':''}>Refresh account</button><button data-action="account-signout" class="danger">Sign out…</button>`:`<button class="primary" data-action="account-login" ${busy?'disabled':''}>${p?'Reconnect Tinfoil Chat':'Sign in to Tinfoil Chat'}</button>${p?'<button data-action="account-signout">Sign out…</button>':''}`}</div>
    <section class="account-section"><h3>Connection for new requests</h3><div class="account-modes" role="group" aria-label="Connection mode"><button data-action="account-mode-chat" aria-pressed="${chat}" ${busy||waiting?'disabled':''}><strong>Tinfoil Chat</strong><span>Your signed-in subscription</span></button><button data-action="account-mode-api" aria-pressed="${!chat}" ${busy||waiting?'disabled':''}><strong>API key</strong><span>Separate developer access</span></button></div><p>Selected: <strong>${active}</strong>. No automatic fallback between billing modes.</p>${!chat?`<button data-action="account-api">${s.hasKey?'Manage saved API key':'Add an API key'}</button>`:usable&&a.entitlement==='active'?`<button data-action="account-connect" ${busy?'disabled':''}>Verify enclave & load models</button>`:''}</section>
    ${p?`<details class="account-section account-details" data-key="account-usage"><summary>Subscription & usage</summary><dl class="account-facts"><div><dt>Chat access</dt><dd>${a.entitlement==='active'?'Token issued by Tinfoil':a.entitlement==='subscription-required'?'Subscription required':a.entitlement==='rate-limited'?'Usage limit reached':'Not checked'}</dd></div><div><dt>Subscription status</dt><dd>${e(p.subscriptionStatus??'Not reported')}</dd></div><div><dt>Subscription expiry</dt><dd>${date(p.subscriptionExpiresAt)}</dd></div><div><dt>Last access check</dt><dd>${date(a.checkedAt)}</dd></div></dl>${a.usage?`<div class="account-usage">${[['Input tokens',a.usage.inputTokens],['Output tokens',a.usage.outputTokens]].map(([label,v])=>{const b=v as import('../core/account.js').TokenBudget|null;return b?`<div class="account-budget"><div><strong>${label}</strong><span>${number(b.remaining)} remaining / ${number(b.max)}</span></div><progress max="${Math.max(1,b.max)}" value="${Math.min(b.max,b.used)}" aria-label="${label} used"></progress></div>`:'';}).join('')}${a.usage.remaining!==null?`<p>${number(a.usage.remaining)} requests remaining${a.usage.maxRequests!==null?' / '+number(a.usage.maxRequests):''}.</p>`:''}<p>Reported reset: ${date(a.usage.resetsAt)}</p></div>`:'<p>Tinfoil has not reported a usage budget for this session.</p>'}<p class="muted">Server-reported snapshots, not a live billing meter. Refresh to check again.</p></details>`:''}
    <details class="account-section account-details"><summary>Session & local workspace</summary>${android?`<p>Sign-in opens Tinfoil’s own sign-in page on a separate screen with its own website storage. Use your email and password; Google and Apple sign-in are not available in the Android app. Profile, password and security changes are handled on Tinfoil’s page.</p><p>While you are signed in, the website session is kept in the app’s private storage and account tokens stay in memory. Chat access renews automatically while the website session lasts. The stored session is deleted when the app next starts, so sign in again after reopening it. Workbench does not import cookies from your regular browser.</p>`:`<p>Sign-in opens Tinfoil’s own sign-in page in a separate, sandboxed window. Profile, password and security changes are handled there.</p><p>The website session and account tokens stay in memory until you sign out or quit. Chat access renews automatically while the website session lasts; after reopening the app, sign in again. Workbench does not import cookies from your regular browser.</p>`}<p>Conversations remain in this device’s encrypted workspace. Signing in does not enable cloud sync or move existing threads to the account. Existing history requires approval before using another connection.</p><p>This uses Tinfoil’s website session, not a registered app sign-in. ${android?'On Android it has not yet been tested with a real account.':'Windows account access has been tested; additional sign-in methods require separate validation.'} No provider-private OAuth endpoint is assumed.</p>${p?`<dl class="account-facts"><div><dt>Account ID</dt><dd>${e(p.id)}</dd></div><div><dt>Inference token expiry</dt><dd>${date(a.tokenExpiresAt)}</dd></div></dl>`:''}</details>
    <p class="account-optional">Custom system instructions are optional—not required. Leave them blank to use provider defaults.</p>`;
}
